// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

// @@protoc_insertion_point(imports)

@class auth_ctx_msg;
@class auth_ctx_msgBuilder;
@class client_login_msg;
@class client_login_msgBuilder;
@class client_login_result_msg;
@class client_login_result_msgBuilder;
@class combo_private_msg;
@class combo_private_msgBuilder;
@class common_reply_error_msg;
@class common_reply_error_msgBuilder;
@class common_update_notice_msg;
@class common_update_notice_msgBuilder;
@class count_offset_selector;
@class count_offset_selectorBuilder;
@class data_selector;
@class data_selectorBuilder;
@class ext_key_info;
@class ext_key_infoBuilder;
@class load_dector_msg;
@class load_dector_msgBuilder;
@class notify_ack_msg;
@class notify_ack_msgBuilder;
@class push_notify_msg;
@class push_notify_msgBuilder;
@class rpc_msg_root;
@class rpc_msg_rootBuilder;
@class server_login_msg;
@class server_login_msgBuilder;
@class server_login_result_msg;
@class server_login_result_msgBuilder;
@class subcribe_msg;
@class subcribe_msgBuilder;
@class sync_notify_msg;
@class sync_notify_msgBuilder;
@class time_offset_selector;
@class time_offset_selectorBuilder;
@class time_range_selector;
@class time_range_selectorBuilder;


typedef NS_ENUM(SInt32, eum_method_type) {
  eum_method_typeCommonErrorRep = 0,
  eum_method_typeLoadDetector = 1,
  eum_method_typeServerLogin = 2,
  eum_method_typeServerLoginRet = 3,
  eum_method_typeClientLogin = 4,
  eum_method_typeClientLoginRet = 5,
  eum_method_typeLoginConflict = 6,
  eum_method_typeIndexRequest = 7,
  eum_method_typeIndexResult = 8,
  eum_method_typeIndexComboResult = 9,
  eum_method_typeErrorFeedback = 10,
  eum_method_typeSubcribeTopic = 11,
  eum_method_typeUnsubcribeTopic = 12,
  eum_method_typePublicTopic = 13,
  eum_method_typeIndexDataRequest = 14,
  eum_method_typeIndexDataResult = 15,
  eum_method_typeRiseDropRequest = 16,
  eum_method_typeRiseDropResult = 17,
  eum_method_typeTgRStockPool = 18,
  eum_method_typeTgRMsgBox = 19,
  eum_method_typeReportReportRequest = 20,
  eum_method_typeReportReportResult = 21,
  eum_method_typeReportLargedealRequest = 22,
  eum_method_typeReportLargedealResult = 23,
  eum_method_typeReportMinuteRequest = 24,
  eum_method_typeReportMinuteResult = 25,
  eum_method_typeReportKlineRequest = 26,
  eum_method_typeReportKlineResult = 27,
  eum_method_typeReportSearchStockRequest = 28,
  eum_method_typeReportSearchStockResult = 29,
  eum_method_typeReportBoardreportRequest = 30,
  eum_method_typeReportBoardreportResult = 31,
  eum_method_typeReportBidDealRequest = 32,
  eum_method_typeReportBidDealResult = 33,
  eum_method_typeReportLastOpenDayRequest = 34,
  eum_method_typeReportLastOpenDayResult = 35,
  eum_method_typeReportBoardreportOptionalRequest = 36,
  eum_method_typeReportBoardreportOptionalResult = 37,
  eum_method_typeReportBoardreportTopRequest = 38,
  eum_method_typeReportBoardreportTopResult = 39,
  eum_method_typeWarningWarningConfigRequest = 40,
  eum_method_typeWarningWarningConfigResult = 41,
  eum_method_typeWarningWarningUserAllStockStatusRequest = 42,
  eum_method_typeWarningWarningUserAllStockStatusResult = 43,
  eum_method_typeWarningSetWarningConfigRequest = 44,
  eum_method_typeWarningSetWarningConfigResult = 45,
  eum_method_typeWarningDeleteUserStockWarningConfigRequest = 46,
  eum_method_typeWarningDeleteUserStockWarningConfigResult = 47,
  eum_method_typeReportIndexKeepRequest = 49,
  eum_method_typeReportIndexKeepResult = 50,
  eum_method_typeReportBlockRelationRequest = 51,
  eum_method_typeReportBlockRelationResult = 52,
  eum_method_typeWarningGetUserStockWarningRecordRequest = 53,
  eum_method_typeWarningGetUserStockWarningRecordResult = 54,
  eum_method_typeReportCodeNameRequest = 55,
  eum_method_typeReportCodeNameResult = 56,
  eum_method_typeEumSyncNotify = 1000,
  eum_method_typeEumPushNotify = 1001,
  eum_method_typeEumPushAck = 1002,
  eum_method_typeEumComboPrivateNotify = 1003,
  eum_method_typeEumAuthKickUser = 2000,
  eum_method_typeEumAuthUserOffline = 2001,
  eum_method_typeEumAuthUserInfoReq = 2002,
  eum_method_typeEumAuthUserInfoRep = 2003,
  eum_method_typeEumMethodEnd = 200000000,
};

BOOL eum_method_typeIsValidValue(eum_method_type value);
NSString *NSStringFromeum_method_type(eum_method_type value);

typedef NS_ENUM(SInt32, eum_rpc_service) {
  eum_rpc_serviceCommonService = 1,
  eum_rpc_serviceReportService = 2,
  eum_rpc_serviceIndexService = 3,
  eum_rpc_serviceInvestmentService = 4,
  eum_rpc_serviceWarningService = 5,
  eum_rpc_serviceEumServiceEnd = 200000000,
};

BOOL eum_rpc_serviceIsValidValue(eum_rpc_service value);
NSString *NSStringFromeum_rpc_service(eum_rpc_service value);

typedef NS_ENUM(SInt32, eum_nofity_type) {
  eum_nofity_typeTgStockInPoolNotify = 0,
  eum_nofity_typeTgStockOutPoolNotify = 1,
  eum_nofity_typeTgStockModifyTargetNofity = 2,
  eum_nofity_typeTgStockModifyStopNodify = 3,
  eum_nofity_typeTgStockBuyNodify = 4,
  eum_nofity_typeTgStockProfitSellNofity = 5,
  eum_nofity_typeTgStockStopLossNofity = 6,
  eum_nofity_typeTgFocusNews = 7,
  eum_nofity_typeTgTrailerAndNotice = 8,
  eum_nofity_typeCommonUpdateNotice = 9,
  eum_nofity_typeIndexStockWarningNotice = 10,
  eum_nofity_typeReportMarketStatusNotify = 11,
};

BOOL eum_nofity_typeIsValidValue(eum_nofity_type value);
NSString *NSStringFromeum_nofity_type(eum_nofity_type value);

typedef NS_ENUM(SInt32, client_login_msglogin_type) {
  client_login_msglogin_typeIndexPc = 0,
  client_login_msglogin_typeIndexMobile = -1002,
  client_login_msglogin_typeTgPc = -1000,
  client_login_msglogin_typeTgMobile = -1001,
};

BOOL client_login_msglogin_typeIsValidValue(client_login_msglogin_type value);
NSString *NSStringFromclient_login_msglogin_type(client_login_msglogin_type value);


@interface CommonRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define ext_key_info_key @"key"
#define ext_key_info_value @"value"
@interface ext_key_info : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasKey_:1;
  BOOL hasValue_:1;
  NSString* key;
  NSString* value;
}
- (BOOL) hasKey;
- (BOOL) hasValue;
@property (readonly, strong) NSString* key;
@property (readonly, strong) NSString* value;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ext_key_infoBuilder*) builder;
+ (ext_key_infoBuilder*) builder;
+ (ext_key_infoBuilder*) builderWithPrototype:(ext_key_info*) prototype;
- (ext_key_infoBuilder*) toBuilder;

+ (ext_key_info*) parseFromData:(NSData*) data;
+ (ext_key_info*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ext_key_info*) parseFromInputStream:(NSInputStream*) input;
+ (ext_key_info*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ext_key_info*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ext_key_info*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ext_key_infoBuilder : PBGeneratedMessageBuilder {
@private
  ext_key_info* resultExtKeyInfo;
}

- (ext_key_info*) defaultInstance;

- (ext_key_infoBuilder*) clear;
- (ext_key_infoBuilder*) clone;

- (ext_key_info*) build;
- (ext_key_info*) buildPartial;

- (ext_key_infoBuilder*) mergeFrom:(ext_key_info*) other;
- (ext_key_infoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ext_key_infoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasKey;
- (NSString*) key;
- (ext_key_infoBuilder*) setKey:(NSString*) value;
- (ext_key_infoBuilder*) clearKey;

- (BOOL) hasValue;
- (NSString*) value;
- (ext_key_infoBuilder*) setValue:(NSString*) value;
- (ext_key_infoBuilder*) clearValue;
@end

#define subcribe_msg_service_type @"serviceType"
#define subcribe_msg_topic @"topic"
@interface subcribe_msg : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasTopic_:1;
  BOOL hasServiceType_:1;
  NSString* topic;
  eum_rpc_service serviceType;
}
- (BOOL) hasServiceType;
- (BOOL) hasTopic;
@property (readonly) eum_rpc_service serviceType;
@property (readonly, strong) NSString* topic;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (subcribe_msgBuilder*) builder;
+ (subcribe_msgBuilder*) builder;
+ (subcribe_msgBuilder*) builderWithPrototype:(subcribe_msg*) prototype;
- (subcribe_msgBuilder*) toBuilder;

+ (subcribe_msg*) parseFromData:(NSData*) data;
+ (subcribe_msg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (subcribe_msg*) parseFromInputStream:(NSInputStream*) input;
+ (subcribe_msg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (subcribe_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (subcribe_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface subcribe_msgBuilder : PBGeneratedMessageBuilder {
@private
  subcribe_msg* resultSubcribeMsg;
}

- (subcribe_msg*) defaultInstance;

- (subcribe_msgBuilder*) clear;
- (subcribe_msgBuilder*) clone;

- (subcribe_msg*) build;
- (subcribe_msg*) buildPartial;

- (subcribe_msgBuilder*) mergeFrom:(subcribe_msg*) other;
- (subcribe_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (subcribe_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasServiceType;
- (eum_rpc_service) serviceType;
- (subcribe_msgBuilder*) setServiceType:(eum_rpc_service) value;
- (subcribe_msgBuilder*) clearServiceType;

- (BOOL) hasTopic;
- (NSString*) topic;
- (subcribe_msgBuilder*) setTopic:(NSString*) value;
- (subcribe_msgBuilder*) clearTopic;
@end

#define sync_notify_msg_uid @"uid"
#define sync_notify_msg_topic @"topic"
#define sync_notify_msg_last_seq @"lastSeq"
#define sync_notify_msg_ext_param @"extParam"
@interface sync_notify_msg : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUid_:1;
  BOOL hasLastSeq_:1;
  BOOL hasTopic_:1;
  SInt64 uid;
  SInt64 lastSeq;
  NSString* topic;
  NSMutableArray * extParamArray;
}
- (BOOL) hasUid;
- (BOOL) hasTopic;
- (BOOL) hasLastSeq;
@property (readonly) SInt64 uid;
@property (readonly, strong) NSString* topic;
@property (readonly) SInt64 lastSeq;
@property (readonly, strong) NSArray * extParam;
- (ext_key_info*)extParamAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (sync_notify_msgBuilder*) builder;
+ (sync_notify_msgBuilder*) builder;
+ (sync_notify_msgBuilder*) builderWithPrototype:(sync_notify_msg*) prototype;
- (sync_notify_msgBuilder*) toBuilder;

+ (sync_notify_msg*) parseFromData:(NSData*) data;
+ (sync_notify_msg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (sync_notify_msg*) parseFromInputStream:(NSInputStream*) input;
+ (sync_notify_msg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (sync_notify_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (sync_notify_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface sync_notify_msgBuilder : PBGeneratedMessageBuilder {
@private
  sync_notify_msg* resultSyncNotifyMsg;
}

- (sync_notify_msg*) defaultInstance;

- (sync_notify_msgBuilder*) clear;
- (sync_notify_msgBuilder*) clone;

- (sync_notify_msg*) build;
- (sync_notify_msg*) buildPartial;

- (sync_notify_msgBuilder*) mergeFrom:(sync_notify_msg*) other;
- (sync_notify_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (sync_notify_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUid;
- (SInt64) uid;
- (sync_notify_msgBuilder*) setUid:(SInt64) value;
- (sync_notify_msgBuilder*) clearUid;

- (BOOL) hasTopic;
- (NSString*) topic;
- (sync_notify_msgBuilder*) setTopic:(NSString*) value;
- (sync_notify_msgBuilder*) clearTopic;

- (BOOL) hasLastSeq;
- (SInt64) lastSeq;
- (sync_notify_msgBuilder*) setLastSeq:(SInt64) value;
- (sync_notify_msgBuilder*) clearLastSeq;

- (NSMutableArray *)extParam;
- (ext_key_info*)extParamAtIndex:(NSUInteger)index;
- (sync_notify_msgBuilder *)addExtParam:(ext_key_info*)value;
- (sync_notify_msgBuilder *)setExtParamArray:(NSArray *)array;
- (sync_notify_msgBuilder *)clearExtParam;
@end

#define push_notify_msg_notify_type @"notifyType"
#define push_notify_msg_msg_seq @"msgSeq"
#define push_notify_msg_sub_msg @"subMsg"
@interface push_notify_msg : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasMsgSeq_:1;
  BOOL hasSubMsg_:1;
  BOOL hasNotifyType_:1;
  SInt64 msgSeq;
  NSData* subMsg;
  eum_nofity_type notifyType;
}
- (BOOL) hasNotifyType;
- (BOOL) hasMsgSeq;
- (BOOL) hasSubMsg;
@property (readonly) eum_nofity_type notifyType;
@property (readonly) SInt64 msgSeq;
@property (readonly, strong) NSData* subMsg;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (push_notify_msgBuilder*) builder;
+ (push_notify_msgBuilder*) builder;
+ (push_notify_msgBuilder*) builderWithPrototype:(push_notify_msg*) prototype;
- (push_notify_msgBuilder*) toBuilder;

+ (push_notify_msg*) parseFromData:(NSData*) data;
+ (push_notify_msg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (push_notify_msg*) parseFromInputStream:(NSInputStream*) input;
+ (push_notify_msg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (push_notify_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (push_notify_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface push_notify_msgBuilder : PBGeneratedMessageBuilder {
@private
  push_notify_msg* resultPushNotifyMsg;
}

- (push_notify_msg*) defaultInstance;

- (push_notify_msgBuilder*) clear;
- (push_notify_msgBuilder*) clone;

- (push_notify_msg*) build;
- (push_notify_msg*) buildPartial;

- (push_notify_msgBuilder*) mergeFrom:(push_notify_msg*) other;
- (push_notify_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (push_notify_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasNotifyType;
- (eum_nofity_type) notifyType;
- (push_notify_msgBuilder*) setNotifyType:(eum_nofity_type) value;
- (push_notify_msgBuilder*) clearNotifyType;

- (BOOL) hasMsgSeq;
- (SInt64) msgSeq;
- (push_notify_msgBuilder*) setMsgSeq:(SInt64) value;
- (push_notify_msgBuilder*) clearMsgSeq;

- (BOOL) hasSubMsg;
- (NSData*) subMsg;
- (push_notify_msgBuilder*) setSubMsg:(NSData*) value;
- (push_notify_msgBuilder*) clearSubMsg;
@end

#define notify_ack_msg_topic @"topic"
#define notify_ack_msg_msg_seq @"msgSeq"
#define notify_ack_msg_uid @"uid"
@interface notify_ack_msg : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasMsgSeq_:1;
  BOOL hasUid_:1;
  BOOL hasTopic_:1;
  SInt64 msgSeq;
  SInt64 uid;
  NSString* topic;
}
- (BOOL) hasTopic;
- (BOOL) hasMsgSeq;
- (BOOL) hasUid;
@property (readonly, strong) NSString* topic;
@property (readonly) SInt64 msgSeq;
@property (readonly) SInt64 uid;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (notify_ack_msgBuilder*) builder;
+ (notify_ack_msgBuilder*) builder;
+ (notify_ack_msgBuilder*) builderWithPrototype:(notify_ack_msg*) prototype;
- (notify_ack_msgBuilder*) toBuilder;

+ (notify_ack_msg*) parseFromData:(NSData*) data;
+ (notify_ack_msg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (notify_ack_msg*) parseFromInputStream:(NSInputStream*) input;
+ (notify_ack_msg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (notify_ack_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (notify_ack_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface notify_ack_msgBuilder : PBGeneratedMessageBuilder {
@private
  notify_ack_msg* resultNotifyAckMsg;
}

- (notify_ack_msg*) defaultInstance;

- (notify_ack_msgBuilder*) clear;
- (notify_ack_msgBuilder*) clone;

- (notify_ack_msg*) build;
- (notify_ack_msg*) buildPartial;

- (notify_ack_msgBuilder*) mergeFrom:(notify_ack_msg*) other;
- (notify_ack_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (notify_ack_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasTopic;
- (NSString*) topic;
- (notify_ack_msgBuilder*) setTopic:(NSString*) value;
- (notify_ack_msgBuilder*) clearTopic;

- (BOOL) hasMsgSeq;
- (SInt64) msgSeq;
- (notify_ack_msgBuilder*) setMsgSeq:(SInt64) value;
- (notify_ack_msgBuilder*) clearMsgSeq;

- (BOOL) hasUid;
- (SInt64) uid;
- (notify_ack_msgBuilder*) setUid:(SInt64) value;
- (notify_ack_msgBuilder*) clearUid;
@end

#define common_update_notice_msg_ext_param @"extParam"
@interface common_update_notice_msg : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  NSMutableArray * extParamArray;
}
@property (readonly, strong) NSArray * extParam;
- (ext_key_info*)extParamAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (common_update_notice_msgBuilder*) builder;
+ (common_update_notice_msgBuilder*) builder;
+ (common_update_notice_msgBuilder*) builderWithPrototype:(common_update_notice_msg*) prototype;
- (common_update_notice_msgBuilder*) toBuilder;

+ (common_update_notice_msg*) parseFromData:(NSData*) data;
+ (common_update_notice_msg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (common_update_notice_msg*) parseFromInputStream:(NSInputStream*) input;
+ (common_update_notice_msg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (common_update_notice_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (common_update_notice_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface common_update_notice_msgBuilder : PBGeneratedMessageBuilder {
@private
  common_update_notice_msg* resultCommonUpdateNoticeMsg;
}

- (common_update_notice_msg*) defaultInstance;

- (common_update_notice_msgBuilder*) clear;
- (common_update_notice_msgBuilder*) clone;

- (common_update_notice_msg*) build;
- (common_update_notice_msg*) buildPartial;

- (common_update_notice_msgBuilder*) mergeFrom:(common_update_notice_msg*) other;
- (common_update_notice_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (common_update_notice_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)extParam;
- (ext_key_info*)extParamAtIndex:(NSUInteger)index;
- (common_update_notice_msgBuilder *)addExtParam:(ext_key_info*)value;
- (common_update_notice_msgBuilder *)setExtParamArray:(NSArray *)array;
- (common_update_notice_msgBuilder *)clearExtParam;
@end

#define combo_private_msg_ack_seq @"ackSeq"
#define combo_private_msg_msgs @"msgs"
@interface combo_private_msg : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasAckSeq_:1;
  SInt64 ackSeq;
  NSMutableArray * msgsArray;
}
- (BOOL) hasAckSeq;
@property (readonly) SInt64 ackSeq;
@property (readonly, strong) NSArray * msgs;
- (common_update_notice_msg*)msgsAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (combo_private_msgBuilder*) builder;
+ (combo_private_msgBuilder*) builder;
+ (combo_private_msgBuilder*) builderWithPrototype:(combo_private_msg*) prototype;
- (combo_private_msgBuilder*) toBuilder;

+ (combo_private_msg*) parseFromData:(NSData*) data;
+ (combo_private_msg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (combo_private_msg*) parseFromInputStream:(NSInputStream*) input;
+ (combo_private_msg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (combo_private_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (combo_private_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface combo_private_msgBuilder : PBGeneratedMessageBuilder {
@private
  combo_private_msg* resultComboPrivateMsg;
}

- (combo_private_msg*) defaultInstance;

- (combo_private_msgBuilder*) clear;
- (combo_private_msgBuilder*) clone;

- (combo_private_msg*) build;
- (combo_private_msg*) buildPartial;

- (combo_private_msgBuilder*) mergeFrom:(combo_private_msg*) other;
- (combo_private_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (combo_private_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasAckSeq;
- (SInt64) ackSeq;
- (combo_private_msgBuilder*) setAckSeq:(SInt64) value;
- (combo_private_msgBuilder*) clearAckSeq;

- (NSMutableArray *)msgs;
- (common_update_notice_msg*)msgsAtIndex:(NSUInteger)index;
- (combo_private_msgBuilder *)addMsgs:(common_update_notice_msg*)value;
- (combo_private_msgBuilder *)setMsgsArray:(NSArray *)array;
- (combo_private_msgBuilder *)clearMsgs;
@end

#define rpc_msg_root_service @"service"
#define rpc_msg_root_method @"method"
#define rpc_msg_root_body @"body"
#define rpc_msg_root_seq @"seq"
#define rpc_msg_root_sid @"sid"
#define rpc_msg_root_cid @"cid"
#define rpc_msg_root_pub_sub @"pubSub"
#define rpc_msg_root_need_auth_ctx @"needAuthCtx"
#define rpc_msg_root_ext @"ext"
@interface rpc_msg_root : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasNeedAuthCtx_:1;
  BOOL hasPubSub_:1;
  BOOL hasBody_:1;
  BOOL hasSeq_:1;
  BOOL hasSid_:1;
  BOOL hasCid_:1;
  BOOL hasService_:1;
  BOOL hasMethod_:1;
  BOOL needAuthCtx_:1;
  NSString* pubSub;
  NSData* body;
  UInt32 seq;
  UInt32 sid;
  UInt32 cid;
  eum_rpc_service service;
  eum_method_type method;
  NSMutableArray * extArray;
}
- (BOOL) hasService;
- (BOOL) hasMethod;
- (BOOL) hasBody;
- (BOOL) hasSeq;
- (BOOL) hasSid;
- (BOOL) hasCid;
- (BOOL) hasPubSub;
- (BOOL) hasNeedAuthCtx;
@property (readonly) eum_rpc_service service;
@property (readonly) eum_method_type method;
@property (readonly, strong) NSData* body;
@property (readonly) UInt32 seq;
@property (readonly) UInt32 sid;
@property (readonly) UInt32 cid;
@property (readonly, strong) NSString* pubSub;
- (BOOL) needAuthCtx;
@property (readonly, strong) NSArray * ext;
- (ext_key_info*)extAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (rpc_msg_rootBuilder*) builder;
+ (rpc_msg_rootBuilder*) builder;
+ (rpc_msg_rootBuilder*) builderWithPrototype:(rpc_msg_root*) prototype;
- (rpc_msg_rootBuilder*) toBuilder;

+ (rpc_msg_root*) parseFromData:(NSData*) data;
+ (rpc_msg_root*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (rpc_msg_root*) parseFromInputStream:(NSInputStream*) input;
+ (rpc_msg_root*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (rpc_msg_root*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (rpc_msg_root*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface rpc_msg_rootBuilder : PBGeneratedMessageBuilder {
@private
  rpc_msg_root* resultRpcMsgRoot;
}

- (rpc_msg_root*) defaultInstance;

- (rpc_msg_rootBuilder*) clear;
- (rpc_msg_rootBuilder*) clone;

- (rpc_msg_root*) build;
- (rpc_msg_root*) buildPartial;

- (rpc_msg_rootBuilder*) mergeFrom:(rpc_msg_root*) other;
- (rpc_msg_rootBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (rpc_msg_rootBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasService;
- (eum_rpc_service) service;
- (rpc_msg_rootBuilder*) setService:(eum_rpc_service) value;
- (rpc_msg_rootBuilder*) clearService;

- (BOOL) hasMethod;
- (eum_method_type) method;
- (rpc_msg_rootBuilder*) setMethod:(eum_method_type) value;
- (rpc_msg_rootBuilder*) clearMethod;

- (BOOL) hasBody;
- (NSData*) body;
- (rpc_msg_rootBuilder*) setBody:(NSData*) value;
- (rpc_msg_rootBuilder*) clearBody;

- (BOOL) hasSeq;
- (UInt32) seq;
- (rpc_msg_rootBuilder*) setSeq:(UInt32) value;
- (rpc_msg_rootBuilder*) clearSeq;

- (BOOL) hasSid;
- (UInt32) sid;
- (rpc_msg_rootBuilder*) setSid:(UInt32) value;
- (rpc_msg_rootBuilder*) clearSid;

- (BOOL) hasCid;
- (UInt32) cid;
- (rpc_msg_rootBuilder*) setCid:(UInt32) value;
- (rpc_msg_rootBuilder*) clearCid;

- (BOOL) hasPubSub;
- (NSString*) pubSub;
- (rpc_msg_rootBuilder*) setPubSub:(NSString*) value;
- (rpc_msg_rootBuilder*) clearPubSub;

- (BOOL) hasNeedAuthCtx;
- (BOOL) needAuthCtx;
- (rpc_msg_rootBuilder*) setNeedAuthCtx:(BOOL) value;
- (rpc_msg_rootBuilder*) clearNeedAuthCtx;

- (NSMutableArray *)ext;
- (ext_key_info*)extAtIndex:(NSUInteger)index;
- (rpc_msg_rootBuilder *)addExt:(ext_key_info*)value;
- (rpc_msg_rootBuilder *)setExtArray:(NSArray *)array;
- (rpc_msg_rootBuilder *)clearExt;
@end

#define common_reply_error_msg_org_type @"orgType"
#define common_reply_error_msg_error @"error"
@interface common_reply_error_msg : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasError_:1;
  BOOL hasOrgType_:1;
  NSString* error;
  eum_method_type orgType;
}
- (BOOL) hasOrgType;
- (BOOL) hasError;
@property (readonly) eum_method_type orgType;
@property (readonly, strong) NSString* error;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (common_reply_error_msgBuilder*) builder;
+ (common_reply_error_msgBuilder*) builder;
+ (common_reply_error_msgBuilder*) builderWithPrototype:(common_reply_error_msg*) prototype;
- (common_reply_error_msgBuilder*) toBuilder;

+ (common_reply_error_msg*) parseFromData:(NSData*) data;
+ (common_reply_error_msg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (common_reply_error_msg*) parseFromInputStream:(NSInputStream*) input;
+ (common_reply_error_msg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (common_reply_error_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (common_reply_error_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface common_reply_error_msgBuilder : PBGeneratedMessageBuilder {
@private
  common_reply_error_msg* resultCommonReplyErrorMsg;
}

- (common_reply_error_msg*) defaultInstance;

- (common_reply_error_msgBuilder*) clear;
- (common_reply_error_msgBuilder*) clone;

- (common_reply_error_msg*) build;
- (common_reply_error_msg*) buildPartial;

- (common_reply_error_msgBuilder*) mergeFrom:(common_reply_error_msg*) other;
- (common_reply_error_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (common_reply_error_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasOrgType;
- (eum_method_type) orgType;
- (common_reply_error_msgBuilder*) setOrgType:(eum_method_type) value;
- (common_reply_error_msgBuilder*) clearOrgType;

- (BOOL) hasError;
- (NSString*) error;
- (common_reply_error_msgBuilder*) setError:(NSString*) value;
- (common_reply_error_msgBuilder*) clearError;
@end

#define load_dector_msg_Req @"req"
#define load_dector_msg_load_factor @"loadFactor"
#define load_dector_msg_connect_count @"connectCount"
#define load_dector_msg_send_time @"sendTime"
@interface load_dector_msg : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasReq_:1;
  BOOL hasLoadFactor_:1;
  BOOL hasConnectCount_:1;
  BOOL hasSendTime_:1;
  BOOL req_:1;
  UInt32 loadFactor;
  UInt32 connectCount;
  UInt32 sendTime;
}
- (BOOL) hasReq;
- (BOOL) hasLoadFactor;
- (BOOL) hasConnectCount;
- (BOOL) hasSendTime;
- (BOOL) req;
@property (readonly) UInt32 loadFactor;
@property (readonly) UInt32 connectCount;
@property (readonly) UInt32 sendTime;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (load_dector_msgBuilder*) builder;
+ (load_dector_msgBuilder*) builder;
+ (load_dector_msgBuilder*) builderWithPrototype:(load_dector_msg*) prototype;
- (load_dector_msgBuilder*) toBuilder;

+ (load_dector_msg*) parseFromData:(NSData*) data;
+ (load_dector_msg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (load_dector_msg*) parseFromInputStream:(NSInputStream*) input;
+ (load_dector_msg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (load_dector_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (load_dector_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface load_dector_msgBuilder : PBGeneratedMessageBuilder {
@private
  load_dector_msg* resultLoadDectorMsg;
}

- (load_dector_msg*) defaultInstance;

- (load_dector_msgBuilder*) clear;
- (load_dector_msgBuilder*) clone;

- (load_dector_msg*) build;
- (load_dector_msg*) buildPartial;

- (load_dector_msgBuilder*) mergeFrom:(load_dector_msg*) other;
- (load_dector_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (load_dector_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasReq;
- (BOOL) req;
- (load_dector_msgBuilder*) setReq:(BOOL) value;
- (load_dector_msgBuilder*) clearReq;

- (BOOL) hasLoadFactor;
- (UInt32) loadFactor;
- (load_dector_msgBuilder*) setLoadFactor:(UInt32) value;
- (load_dector_msgBuilder*) clearLoadFactor;

- (BOOL) hasConnectCount;
- (UInt32) connectCount;
- (load_dector_msgBuilder*) setConnectCount:(UInt32) value;
- (load_dector_msgBuilder*) clearConnectCount;

- (BOOL) hasSendTime;
- (UInt32) sendTime;
- (load_dector_msgBuilder*) setSendTime:(UInt32) value;
- (load_dector_msgBuilder*) clearSendTime;
@end

#define server_login_msg_name @"name"
#define server_login_msg_password @"password"
@interface server_login_msg : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasName_:1;
  BOOL hasPassword_:1;
  NSString* name;
  NSString* password;
}
- (BOOL) hasName;
- (BOOL) hasPassword;
@property (readonly, strong) NSString* name;
@property (readonly, strong) NSString* password;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (server_login_msgBuilder*) builder;
+ (server_login_msgBuilder*) builder;
+ (server_login_msgBuilder*) builderWithPrototype:(server_login_msg*) prototype;
- (server_login_msgBuilder*) toBuilder;

+ (server_login_msg*) parseFromData:(NSData*) data;
+ (server_login_msg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (server_login_msg*) parseFromInputStream:(NSInputStream*) input;
+ (server_login_msg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (server_login_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (server_login_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface server_login_msgBuilder : PBGeneratedMessageBuilder {
@private
  server_login_msg* resultServerLoginMsg;
}

- (server_login_msg*) defaultInstance;

- (server_login_msgBuilder*) clear;
- (server_login_msgBuilder*) clone;

- (server_login_msg*) build;
- (server_login_msg*) buildPartial;

- (server_login_msgBuilder*) mergeFrom:(server_login_msg*) other;
- (server_login_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (server_login_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (server_login_msgBuilder*) setName:(NSString*) value;
- (server_login_msgBuilder*) clearName;

- (BOOL) hasPassword;
- (NSString*) password;
- (server_login_msgBuilder*) setPassword:(NSString*) value;
- (server_login_msgBuilder*) clearPassword;
@end

#define server_login_result_msg_result @"result"
@interface server_login_result_msg : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasResult_:1;
  BOOL result_:1;
}
- (BOOL) hasResult;
- (BOOL) result;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (server_login_result_msgBuilder*) builder;
+ (server_login_result_msgBuilder*) builder;
+ (server_login_result_msgBuilder*) builderWithPrototype:(server_login_result_msg*) prototype;
- (server_login_result_msgBuilder*) toBuilder;

+ (server_login_result_msg*) parseFromData:(NSData*) data;
+ (server_login_result_msg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (server_login_result_msg*) parseFromInputStream:(NSInputStream*) input;
+ (server_login_result_msg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (server_login_result_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (server_login_result_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface server_login_result_msgBuilder : PBGeneratedMessageBuilder {
@private
  server_login_result_msg* resultServerLoginResultMsg;
}

- (server_login_result_msg*) defaultInstance;

- (server_login_result_msgBuilder*) clear;
- (server_login_result_msgBuilder*) clone;

- (server_login_result_msg*) build;
- (server_login_result_msg*) buildPartial;

- (server_login_result_msgBuilder*) mergeFrom:(server_login_result_msg*) other;
- (server_login_result_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (server_login_result_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasResult;
- (BOOL) result;
- (server_login_result_msgBuilder*) setResult:(BOOL) value;
- (server_login_result_msgBuilder*) clearResult;
@end

#define client_login_msg_name @"name"
#define client_login_msg_password @"password"
#define client_login_msg_bios @"bios"
#define client_login_msg_mac @"mac"
#define client_login_msg_hdd @"hdd"
#define client_login_msg_cpu @"cpu"
#define client_login_msg_ip @"ip"
#define client_login_msg_ltype @"ltype"
#define client_login_msg_sid @"sid"
#define client_login_msg_cid @"cid"
@interface client_login_msg : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasName_:1;
  BOOL hasPassword_:1;
  BOOL hasBios_:1;
  BOOL hasMac_:1;
  BOOL hasHdd_:1;
  BOOL hasCpu_:1;
  BOOL hasIp_:1;
  BOOL hasSid_:1;
  BOOL hasCid_:1;
  BOOL hasLtype_:1;
  NSString* name;
  NSString* password;
  NSString* bios;
  NSString* mac;
  NSString* hdd;
  NSString* cpu;
  NSString* ip;
  UInt32 sid;
  UInt32 cid;
  client_login_msglogin_type ltype;
}
- (BOOL) hasName;
- (BOOL) hasPassword;
- (BOOL) hasBios;
- (BOOL) hasMac;
- (BOOL) hasHdd;
- (BOOL) hasCpu;
- (BOOL) hasIp;
- (BOOL) hasLtype;
- (BOOL) hasSid;
- (BOOL) hasCid;
@property (readonly, strong) NSString* name;
@property (readonly, strong) NSString* password;
@property (readonly, strong) NSString* bios;
@property (readonly, strong) NSString* mac;
@property (readonly, strong) NSString* hdd;
@property (readonly, strong) NSString* cpu;
@property (readonly, strong) NSString* ip;
@property (readonly) client_login_msglogin_type ltype;
@property (readonly) UInt32 sid;
@property (readonly) UInt32 cid;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (client_login_msgBuilder*) builder;
+ (client_login_msgBuilder*) builder;
+ (client_login_msgBuilder*) builderWithPrototype:(client_login_msg*) prototype;
- (client_login_msgBuilder*) toBuilder;

+ (client_login_msg*) parseFromData:(NSData*) data;
+ (client_login_msg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (client_login_msg*) parseFromInputStream:(NSInputStream*) input;
+ (client_login_msg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (client_login_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (client_login_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface client_login_msgBuilder : PBGeneratedMessageBuilder {
@private
  client_login_msg* resultClientLoginMsg;
}

- (client_login_msg*) defaultInstance;

- (client_login_msgBuilder*) clear;
- (client_login_msgBuilder*) clone;

- (client_login_msg*) build;
- (client_login_msg*) buildPartial;

- (client_login_msgBuilder*) mergeFrom:(client_login_msg*) other;
- (client_login_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (client_login_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (client_login_msgBuilder*) setName:(NSString*) value;
- (client_login_msgBuilder*) clearName;

- (BOOL) hasPassword;
- (NSString*) password;
- (client_login_msgBuilder*) setPassword:(NSString*) value;
- (client_login_msgBuilder*) clearPassword;

- (BOOL) hasBios;
- (NSString*) bios;
- (client_login_msgBuilder*) setBios:(NSString*) value;
- (client_login_msgBuilder*) clearBios;

- (BOOL) hasMac;
- (NSString*) mac;
- (client_login_msgBuilder*) setMac:(NSString*) value;
- (client_login_msgBuilder*) clearMac;

- (BOOL) hasHdd;
- (NSString*) hdd;
- (client_login_msgBuilder*) setHdd:(NSString*) value;
- (client_login_msgBuilder*) clearHdd;

- (BOOL) hasCpu;
- (NSString*) cpu;
- (client_login_msgBuilder*) setCpu:(NSString*) value;
- (client_login_msgBuilder*) clearCpu;

- (BOOL) hasIp;
- (NSString*) ip;
- (client_login_msgBuilder*) setIp:(NSString*) value;
- (client_login_msgBuilder*) clearIp;

- (BOOL) hasLtype;
- (client_login_msglogin_type) ltype;
- (client_login_msgBuilder*) setLtype:(client_login_msglogin_type) value;
- (client_login_msgBuilder*) clearLtype;

- (BOOL) hasSid;
- (UInt32) sid;
- (client_login_msgBuilder*) setSid:(UInt32) value;
- (client_login_msgBuilder*) clearSid;

- (BOOL) hasCid;
- (UInt32) cid;
- (client_login_msgBuilder*) setCid:(UInt32) value;
- (client_login_msgBuilder*) clearCid;
@end

#define auth_ctx_msg_auth_services @"authServices"
#define auth_ctx_msg_topics @"topics"
#define auth_ctx_msg_ext @"ext"
@interface auth_ctx_msg : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  NSMutableArray * topicsArray;
  NSMutableArray * extArray;
  PBAppendableArray * authServicesArray;
}
@property (readonly, strong) PBArray * authServices;
@property (readonly, strong) NSArray * topics;
@property (readonly, strong) NSArray * ext;
- (eum_rpc_service)authServicesAtIndex:(NSUInteger)index;
- (subcribe_msg*)topicsAtIndex:(NSUInteger)index;
- (ext_key_info*)extAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (auth_ctx_msgBuilder*) builder;
+ (auth_ctx_msgBuilder*) builder;
+ (auth_ctx_msgBuilder*) builderWithPrototype:(auth_ctx_msg*) prototype;
- (auth_ctx_msgBuilder*) toBuilder;

+ (auth_ctx_msg*) parseFromData:(NSData*) data;
+ (auth_ctx_msg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (auth_ctx_msg*) parseFromInputStream:(NSInputStream*) input;
+ (auth_ctx_msg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (auth_ctx_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (auth_ctx_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface auth_ctx_msgBuilder : PBGeneratedMessageBuilder {
@private
  auth_ctx_msg* resultAuthCtxMsg;
}

- (auth_ctx_msg*) defaultInstance;

- (auth_ctx_msgBuilder*) clear;
- (auth_ctx_msgBuilder*) clone;

- (auth_ctx_msg*) build;
- (auth_ctx_msg*) buildPartial;

- (auth_ctx_msgBuilder*) mergeFrom:(auth_ctx_msg*) other;
- (auth_ctx_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (auth_ctx_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (PBAppendableArray *)authServices;
- (eum_rpc_service)authServicesAtIndex:(NSUInteger)index;
- (auth_ctx_msgBuilder *)addAuthServices:(eum_rpc_service)value;
- (auth_ctx_msgBuilder *)setAuthServicesArray:(NSArray *)array;
- (auth_ctx_msgBuilder *)setAuthServicesValues:(const eum_rpc_service *)values count:(NSUInteger)count;
- (auth_ctx_msgBuilder *)clearAuthServices;

- (NSMutableArray *)topics;
- (subcribe_msg*)topicsAtIndex:(NSUInteger)index;
- (auth_ctx_msgBuilder *)addTopics:(subcribe_msg*)value;
- (auth_ctx_msgBuilder *)setTopicsArray:(NSArray *)array;
- (auth_ctx_msgBuilder *)clearTopics;

- (NSMutableArray *)ext;
- (ext_key_info*)extAtIndex:(NSUInteger)index;
- (auth_ctx_msgBuilder *)addExt:(ext_key_info*)value;
- (auth_ctx_msgBuilder *)setExtArray:(NSArray *)array;
- (auth_ctx_msgBuilder *)clearExt;
@end

#define client_login_result_msg_result @"result"
#define client_login_result_msg_msg @"msg"
#define client_login_result_msg_ext @"ext"
#define client_login_result_msg_ltype @"ltype"
#define client_login_result_msg_sid @"sid"
#define client_login_result_msg_cid @"cid"
#define client_login_result_msg_auths @"auths"
@interface client_login_result_msg : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasResult_:1;
  BOOL hasLtype_:1;
  BOOL hasMsg_:1;
  BOOL hasAuths_:1;
  BOOL hasSid_:1;
  BOOL hasCid_:1;
  BOOL result_:1;
  SInt32 ltype;
  NSString* msg;
  auth_ctx_msg* auths;
  UInt32 sid;
  UInt32 cid;
  NSMutableArray * extArray;
}
- (BOOL) hasResult;
- (BOOL) hasMsg;
- (BOOL) hasLtype;
- (BOOL) hasSid;
- (BOOL) hasCid;
- (BOOL) hasAuths;
- (BOOL) result;
@property (readonly, strong) NSString* msg;
@property (readonly, strong) NSArray * ext;
@property (readonly) SInt32 ltype;
@property (readonly) UInt32 sid;
@property (readonly) UInt32 cid;
@property (readonly, strong) auth_ctx_msg* auths;
- (ext_key_info*)extAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (client_login_result_msgBuilder*) builder;
+ (client_login_result_msgBuilder*) builder;
+ (client_login_result_msgBuilder*) builderWithPrototype:(client_login_result_msg*) prototype;
- (client_login_result_msgBuilder*) toBuilder;

+ (client_login_result_msg*) parseFromData:(NSData*) data;
+ (client_login_result_msg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (client_login_result_msg*) parseFromInputStream:(NSInputStream*) input;
+ (client_login_result_msg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (client_login_result_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (client_login_result_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface client_login_result_msgBuilder : PBGeneratedMessageBuilder {
@private
  client_login_result_msg* resultClientLoginResultMsg;
}

- (client_login_result_msg*) defaultInstance;

- (client_login_result_msgBuilder*) clear;
- (client_login_result_msgBuilder*) clone;

- (client_login_result_msg*) build;
- (client_login_result_msg*) buildPartial;

- (client_login_result_msgBuilder*) mergeFrom:(client_login_result_msg*) other;
- (client_login_result_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (client_login_result_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasResult;
- (BOOL) result;
- (client_login_result_msgBuilder*) setResult:(BOOL) value;
- (client_login_result_msgBuilder*) clearResult;

- (BOOL) hasMsg;
- (NSString*) msg;
- (client_login_result_msgBuilder*) setMsg:(NSString*) value;
- (client_login_result_msgBuilder*) clearMsg;

- (NSMutableArray *)ext;
- (ext_key_info*)extAtIndex:(NSUInteger)index;
- (client_login_result_msgBuilder *)addExt:(ext_key_info*)value;
- (client_login_result_msgBuilder *)setExtArray:(NSArray *)array;
- (client_login_result_msgBuilder *)clearExt;

- (BOOL) hasLtype;
- (SInt32) ltype;
- (client_login_result_msgBuilder*) setLtype:(SInt32) value;
- (client_login_result_msgBuilder*) clearLtype;

- (BOOL) hasSid;
- (UInt32) sid;
- (client_login_result_msgBuilder*) setSid:(UInt32) value;
- (client_login_result_msgBuilder*) clearSid;

- (BOOL) hasCid;
- (UInt32) cid;
- (client_login_result_msgBuilder*) setCid:(UInt32) value;
- (client_login_result_msgBuilder*) clearCid;

- (BOOL) hasAuths;
- (auth_ctx_msg*) auths;
- (client_login_result_msgBuilder*) setAuths:(auth_ctx_msg*) value;
- (client_login_result_msgBuilder*) setAuthsBuilder:(auth_ctx_msgBuilder*) builderForValue;
- (client_login_result_msgBuilder*) mergeAuths:(auth_ctx_msg*) value;
- (client_login_result_msgBuilder*) clearAuths;
@end

#define time_range_selector_begin @"begin"
#define time_range_selector_end @"end"
@interface time_range_selector : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasBegin_:1;
  BOOL hasEnd_:1;
  UInt32 begin;
  UInt32 end;
}
- (BOOL) hasBegin;
- (BOOL) hasEnd;
@property (readonly) UInt32 begin;
@property (readonly) UInt32 end;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (time_range_selectorBuilder*) builder;
+ (time_range_selectorBuilder*) builder;
+ (time_range_selectorBuilder*) builderWithPrototype:(time_range_selector*) prototype;
- (time_range_selectorBuilder*) toBuilder;

+ (time_range_selector*) parseFromData:(NSData*) data;
+ (time_range_selector*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (time_range_selector*) parseFromInputStream:(NSInputStream*) input;
+ (time_range_selector*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (time_range_selector*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (time_range_selector*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface time_range_selectorBuilder : PBGeneratedMessageBuilder {
@private
  time_range_selector* resultTimeRangeSelector;
}

- (time_range_selector*) defaultInstance;

- (time_range_selectorBuilder*) clear;
- (time_range_selectorBuilder*) clone;

- (time_range_selector*) build;
- (time_range_selector*) buildPartial;

- (time_range_selectorBuilder*) mergeFrom:(time_range_selector*) other;
- (time_range_selectorBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (time_range_selectorBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasBegin;
- (UInt32) begin;
- (time_range_selectorBuilder*) setBegin:(UInt32) value;
- (time_range_selectorBuilder*) clearBegin;

- (BOOL) hasEnd;
- (UInt32) end;
- (time_range_selectorBuilder*) setEnd:(UInt32) value;
- (time_range_selectorBuilder*) clearEnd;
@end

#define count_offset_selector_offset @"offset"
#define count_offset_selector_count @"count"
@interface count_offset_selector : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasCount_:1;
  BOOL hasOffset_:1;
  SInt32 count;
  UInt32 offset;
}
- (BOOL) hasOffset;
- (BOOL) hasCount;
@property (readonly) UInt32 offset;
@property (readonly) SInt32 count;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (count_offset_selectorBuilder*) builder;
+ (count_offset_selectorBuilder*) builder;
+ (count_offset_selectorBuilder*) builderWithPrototype:(count_offset_selector*) prototype;
- (count_offset_selectorBuilder*) toBuilder;

+ (count_offset_selector*) parseFromData:(NSData*) data;
+ (count_offset_selector*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (count_offset_selector*) parseFromInputStream:(NSInputStream*) input;
+ (count_offset_selector*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (count_offset_selector*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (count_offset_selector*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface count_offset_selectorBuilder : PBGeneratedMessageBuilder {
@private
  count_offset_selector* resultCountOffsetSelector;
}

- (count_offset_selector*) defaultInstance;

- (count_offset_selectorBuilder*) clear;
- (count_offset_selectorBuilder*) clone;

- (count_offset_selector*) build;
- (count_offset_selector*) buildPartial;

- (count_offset_selectorBuilder*) mergeFrom:(count_offset_selector*) other;
- (count_offset_selectorBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (count_offset_selectorBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasOffset;
- (UInt32) offset;
- (count_offset_selectorBuilder*) setOffset:(UInt32) value;
- (count_offset_selectorBuilder*) clearOffset;

- (BOOL) hasCount;
- (SInt32) count;
- (count_offset_selectorBuilder*) setCount:(SInt32) value;
- (count_offset_selectorBuilder*) clearCount;
@end

#define time_offset_selector_origin_time @"originTime"
#define time_offset_selector_count @"count"
@interface time_offset_selector : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasCount_:1;
  BOOL hasOriginTime_:1;
  SInt32 count;
  UInt32 originTime;
}
- (BOOL) hasOriginTime;
- (BOOL) hasCount;
@property (readonly) UInt32 originTime;
@property (readonly) SInt32 count;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (time_offset_selectorBuilder*) builder;
+ (time_offset_selectorBuilder*) builder;
+ (time_offset_selectorBuilder*) builderWithPrototype:(time_offset_selector*) prototype;
- (time_offset_selectorBuilder*) toBuilder;

+ (time_offset_selector*) parseFromData:(NSData*) data;
+ (time_offset_selector*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (time_offset_selector*) parseFromInputStream:(NSInputStream*) input;
+ (time_offset_selector*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (time_offset_selector*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (time_offset_selector*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface time_offset_selectorBuilder : PBGeneratedMessageBuilder {
@private
  time_offset_selector* resultTimeOffsetSelector;
}

- (time_offset_selector*) defaultInstance;

- (time_offset_selectorBuilder*) clear;
- (time_offset_selectorBuilder*) clone;

- (time_offset_selector*) build;
- (time_offset_selector*) buildPartial;

- (time_offset_selectorBuilder*) mergeFrom:(time_offset_selector*) other;
- (time_offset_selectorBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (time_offset_selectorBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasOriginTime;
- (UInt32) originTime;
- (time_offset_selectorBuilder*) setOriginTime:(UInt32) value;
- (time_offset_selectorBuilder*) clearOriginTime;

- (BOOL) hasCount;
- (SInt32) count;
- (time_offset_selectorBuilder*) setCount:(SInt32) value;
- (time_offset_selectorBuilder*) clearCount;
@end

#define data_selector_selector_type @"selectorType"
#define data_selector_selector @"selector"
@interface data_selector : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasSelector_:1;
  BOOL hasSelectorType_:1;
  NSData* selector;
  UInt32 selectorType;
}
- (BOOL) hasSelectorType;
- (BOOL) hasSelector;
@property (readonly) UInt32 selectorType;
@property (readonly, strong) NSData* selector;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (data_selectorBuilder*) builder;
+ (data_selectorBuilder*) builder;
+ (data_selectorBuilder*) builderWithPrototype:(data_selector*) prototype;
- (data_selectorBuilder*) toBuilder;

+ (data_selector*) parseFromData:(NSData*) data;
+ (data_selector*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (data_selector*) parseFromInputStream:(NSInputStream*) input;
+ (data_selector*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (data_selector*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (data_selector*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface data_selectorBuilder : PBGeneratedMessageBuilder {
@private
  data_selector* resultDataSelector;
}

- (data_selector*) defaultInstance;

- (data_selectorBuilder*) clear;
- (data_selectorBuilder*) clone;

- (data_selector*) build;
- (data_selector*) buildPartial;

- (data_selectorBuilder*) mergeFrom:(data_selector*) other;
- (data_selectorBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (data_selectorBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSelectorType;
- (UInt32) selectorType;
- (data_selectorBuilder*) setSelectorType:(UInt32) value;
- (data_selectorBuilder*) clearSelectorType;

- (BOOL) hasSelector;
- (NSData*) selector;
- (data_selectorBuilder*) setSelector:(NSData*) value;
- (data_selectorBuilder*) clearSelector;
@end


// @@protoc_insertion_point(global_scope)
