// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

#import "Common.pb.h"
// @@protoc_insertion_point(imports)

@class auth_ctx_msg;
@class auth_ctx_msgBuilder;
@class client_login_msg;
@class client_login_msgBuilder;
@class client_login_result_msg;
@class client_login_result_msgBuilder;
@class combo_private_msg;
@class combo_private_msgBuilder;
@class common_reply_error_msg;
@class common_reply_error_msgBuilder;
@class common_update_notice_msg;
@class common_update_notice_msgBuilder;
@class count_offset_selector;
@class count_offset_selectorBuilder;
@class data_selector;
@class data_selectorBuilder;
@class ext_key_info;
@class ext_key_infoBuilder;
@class load_dector_msg;
@class load_dector_msgBuilder;
@class notify_ack_msg;
@class notify_ack_msgBuilder;
@class push_notify_msg;
@class push_notify_msgBuilder;
@class rpc_msg_root;
@class rpc_msg_rootBuilder;
@class server_login_msg;
@class server_login_msgBuilder;
@class server_login_result_msg;
@class server_login_result_msgBuilder;
@class subcribe_msg;
@class subcribe_msgBuilder;
@class sync_notify_msg;
@class sync_notify_msgBuilder;
@class tg_focus_news_notify_msg;
@class tg_focus_news_notify_msgBuilder;
@class tg_msg_box_combo_msg;
@class tg_msg_box_combo_msgBuilder;
@class tg_msg_box_combo_msgtg_msg_node;
@class tg_msg_box_combo_msgtg_msg_nodeBuilder;
@class tg_req_msg_box_msg;
@class tg_req_msg_box_msgBuilder;
@class tg_req_stock_pool_msg;
@class tg_req_stock_pool_msgBuilder;
@class tg_stock_att;
@class tg_stock_attBuilder;
@class tg_stock_buy_notify_msg;
@class tg_stock_buy_notify_msgBuilder;
@class tg_stock_in_pool_notify_msg;
@class tg_stock_in_pool_notify_msgBuilder;
@class tg_stock_new_stop_notify_msg;
@class tg_stock_new_stop_notify_msgBuilder;
@class tg_stock_new_target_notify_msg;
@class tg_stock_new_target_notify_msgBuilder;
@class tg_stock_out_pool_notify_msg;
@class tg_stock_out_pool_notify_msgBuilder;
@class tg_stock_pool_msg;
@class tg_stock_pool_msgBuilder;
@class tg_stock_profit_notify_msg;
@class tg_stock_profit_notify_msgBuilder;
@class tg_stock_stop_notify_msg;
@class tg_stock_stop_notify_msgBuilder;
@class tg_trailer_notify_msg;
@class tg_trailer_notify_msgBuilder;
@class time_offset_selector;
@class time_offset_selectorBuilder;
@class time_range_selector;
@class time_range_selectorBuilder;


typedef NS_ENUM(SInt32, tg_investment_period_type) {
  tg_investment_period_typeTgInvestmentPeriodTypeNull = 0,
  tg_investment_period_typeTgShortPeriod = 1,
  tg_investment_period_typeTgMidPeriod = 2,
  tg_investment_period_typeTgLongPeriod = 3,
};

BOOL tg_investment_period_typeIsValidValue(tg_investment_period_type value);
NSString *NSStringFromtg_investment_period_type(tg_investment_period_type value);

typedef NS_ENUM(SInt32, tg_stock_investment_state) {
  tg_stock_investment_stateTgStockInvestmentStateNull = 0,
  tg_stock_investment_stateTgInPool = 1,
  tg_stock_investment_stateTgAutoBuy = 2,
  tg_stock_investment_stateTgManualBuy = 3,
  tg_stock_investment_stateTgHold = 4,
  tg_stock_investment_stateTgOutPool = 5,
  tg_stock_investment_stateTgModifyProfit = 6,
  tg_stock_investment_stateTgModifyStop = 7,
  tg_stock_investment_stateTgAutoProfit = 8,
  tg_stock_investment_stateTgAutoStop = 9,
  tg_stock_investment_stateTgManuallyProfit = 10,
  tg_stock_investment_stateTgManuallyStop = 11,
};

BOOL tg_stock_investment_stateIsValidValue(tg_stock_investment_state value);
NSString *NSStringFromtg_stock_investment_state(tg_stock_investment_state value);


@interface InvestmentRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define tg_stock_att_code @"code"
#define tg_stock_att_date @"date"
#define tg_stock_att_low_buy_pirce @"lowBuyPirce"
#define tg_stock_att_high_buy_price @"highBuyPrice"
#define tg_stock_att_target_price @"targetPrice"
#define tg_stock_att_stop_price @"stopPrice"
#define tg_stock_att_inv_type @"invType"
#define tg_stock_att_buy_state @"buyState"
#define tg_stock_att_current_buy_price @"currentBuyPrice"
#define tg_stock_att_current_sell_price @"currentSellPrice"
@interface tg_stock_att : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasLowBuyPirce_:1;
  BOOL hasHighBuyPrice_:1;
  BOOL hasTargetPrice_:1;
  BOOL hasStopPrice_:1;
  BOOL hasCurrentBuyPrice_:1;
  BOOL hasCurrentSellPrice_:1;
  BOOL hasDate_:1;
  BOOL hasCode_:1;
  BOOL hasInvType_:1;
  BOOL hasBuyState_:1;
  Float32 lowBuyPirce;
  Float32 highBuyPrice;
  Float32 targetPrice;
  Float32 stopPrice;
  Float32 currentBuyPrice;
  Float32 currentSellPrice;
  SInt64 date;
  NSString* code;
  tg_investment_period_type invType;
  tg_stock_investment_state buyState;
}
- (BOOL) hasCode;
- (BOOL) hasDate;
- (BOOL) hasLowBuyPirce;
- (BOOL) hasHighBuyPrice;
- (BOOL) hasTargetPrice;
- (BOOL) hasStopPrice;
- (BOOL) hasInvType;
- (BOOL) hasBuyState;
- (BOOL) hasCurrentBuyPrice;
- (BOOL) hasCurrentSellPrice;
@property (readonly, strong) NSString* code;
@property (readonly) SInt64 date;
@property (readonly) Float32 lowBuyPirce;
@property (readonly) Float32 highBuyPrice;
@property (readonly) Float32 targetPrice;
@property (readonly) Float32 stopPrice;
@property (readonly) tg_investment_period_type invType;
@property (readonly) tg_stock_investment_state buyState;
@property (readonly) Float32 currentBuyPrice;
@property (readonly) Float32 currentSellPrice;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (tg_stock_attBuilder*) builder;
+ (tg_stock_attBuilder*) builder;
+ (tg_stock_attBuilder*) builderWithPrototype:(tg_stock_att*) prototype;
- (tg_stock_attBuilder*) toBuilder;

+ (tg_stock_att*) parseFromData:(NSData*) data;
+ (tg_stock_att*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (tg_stock_att*) parseFromInputStream:(NSInputStream*) input;
+ (tg_stock_att*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (tg_stock_att*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (tg_stock_att*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface tg_stock_attBuilder : PBGeneratedMessageBuilder {
@private
  tg_stock_att* resultTgStockAtt;
}

- (tg_stock_att*) defaultInstance;

- (tg_stock_attBuilder*) clear;
- (tg_stock_attBuilder*) clone;

- (tg_stock_att*) build;
- (tg_stock_att*) buildPartial;

- (tg_stock_attBuilder*) mergeFrom:(tg_stock_att*) other;
- (tg_stock_attBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (tg_stock_attBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCode;
- (NSString*) code;
- (tg_stock_attBuilder*) setCode:(NSString*) value;
- (tg_stock_attBuilder*) clearCode;

- (BOOL) hasDate;
- (SInt64) date;
- (tg_stock_attBuilder*) setDate:(SInt64) value;
- (tg_stock_attBuilder*) clearDate;

- (BOOL) hasLowBuyPirce;
- (Float32) lowBuyPirce;
- (tg_stock_attBuilder*) setLowBuyPirce:(Float32) value;
- (tg_stock_attBuilder*) clearLowBuyPirce;

- (BOOL) hasHighBuyPrice;
- (Float32) highBuyPrice;
- (tg_stock_attBuilder*) setHighBuyPrice:(Float32) value;
- (tg_stock_attBuilder*) clearHighBuyPrice;

- (BOOL) hasTargetPrice;
- (Float32) targetPrice;
- (tg_stock_attBuilder*) setTargetPrice:(Float32) value;
- (tg_stock_attBuilder*) clearTargetPrice;

- (BOOL) hasStopPrice;
- (Float32) stopPrice;
- (tg_stock_attBuilder*) setStopPrice:(Float32) value;
- (tg_stock_attBuilder*) clearStopPrice;

- (BOOL) hasInvType;
- (tg_investment_period_type) invType;
- (tg_stock_attBuilder*) setInvType:(tg_investment_period_type) value;
- (tg_stock_attBuilder*) clearInvType;

- (BOOL) hasBuyState;
- (tg_stock_investment_state) buyState;
- (tg_stock_attBuilder*) setBuyState:(tg_stock_investment_state) value;
- (tg_stock_attBuilder*) clearBuyState;

- (BOOL) hasCurrentBuyPrice;
- (Float32) currentBuyPrice;
- (tg_stock_attBuilder*) setCurrentBuyPrice:(Float32) value;
- (tg_stock_attBuilder*) clearCurrentBuyPrice;

- (BOOL) hasCurrentSellPrice;
- (Float32) currentSellPrice;
- (tg_stock_attBuilder*) setCurrentSellPrice:(Float32) value;
- (tg_stock_attBuilder*) clearCurrentSellPrice;
@end

#define tg_req_stock_pool_msg_version_id @"versionId"
#define tg_req_stock_pool_msg_pid @"pid"
@interface tg_req_stock_pool_msg : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasVersionId_:1;
  BOOL hasPid_:1;
  SInt64 versionId;
  SInt32 pid;
}
- (BOOL) hasVersionId;
- (BOOL) hasPid;
@property (readonly) SInt64 versionId;
@property (readonly) SInt32 pid;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (tg_req_stock_pool_msgBuilder*) builder;
+ (tg_req_stock_pool_msgBuilder*) builder;
+ (tg_req_stock_pool_msgBuilder*) builderWithPrototype:(tg_req_stock_pool_msg*) prototype;
- (tg_req_stock_pool_msgBuilder*) toBuilder;

+ (tg_req_stock_pool_msg*) parseFromData:(NSData*) data;
+ (tg_req_stock_pool_msg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (tg_req_stock_pool_msg*) parseFromInputStream:(NSInputStream*) input;
+ (tg_req_stock_pool_msg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (tg_req_stock_pool_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (tg_req_stock_pool_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface tg_req_stock_pool_msgBuilder : PBGeneratedMessageBuilder {
@private
  tg_req_stock_pool_msg* resultTgReqStockPoolMsg;
}

- (tg_req_stock_pool_msg*) defaultInstance;

- (tg_req_stock_pool_msgBuilder*) clear;
- (tg_req_stock_pool_msgBuilder*) clone;

- (tg_req_stock_pool_msg*) build;
- (tg_req_stock_pool_msg*) buildPartial;

- (tg_req_stock_pool_msgBuilder*) mergeFrom:(tg_req_stock_pool_msg*) other;
- (tg_req_stock_pool_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (tg_req_stock_pool_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasVersionId;
- (SInt64) versionId;
- (tg_req_stock_pool_msgBuilder*) setVersionId:(SInt64) value;
- (tg_req_stock_pool_msgBuilder*) clearVersionId;

- (BOOL) hasPid;
- (SInt32) pid;
- (tg_req_stock_pool_msgBuilder*) setPid:(SInt32) value;
- (tg_req_stock_pool_msgBuilder*) clearPid;
@end

#define tg_stock_pool_msg_version_id @"versionId"
#define tg_stock_pool_msg_stocks @"stocks"
#define tg_stock_pool_msg_position @"position"
@interface tg_stock_pool_msg : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasPosition_:1;
  BOOL hasVersionId_:1;
  Float64 position;
  SInt64 versionId;
  NSMutableArray * stocksArray;
}
- (BOOL) hasVersionId;
- (BOOL) hasPosition;
@property (readonly) SInt64 versionId;
@property (readonly, strong) NSArray * stocks;
@property (readonly) Float64 position;
- (tg_stock_att*)stocksAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (tg_stock_pool_msgBuilder*) builder;
+ (tg_stock_pool_msgBuilder*) builder;
+ (tg_stock_pool_msgBuilder*) builderWithPrototype:(tg_stock_pool_msg*) prototype;
- (tg_stock_pool_msgBuilder*) toBuilder;

+ (tg_stock_pool_msg*) parseFromData:(NSData*) data;
+ (tg_stock_pool_msg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (tg_stock_pool_msg*) parseFromInputStream:(NSInputStream*) input;
+ (tg_stock_pool_msg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (tg_stock_pool_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (tg_stock_pool_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface tg_stock_pool_msgBuilder : PBGeneratedMessageBuilder {
@private
  tg_stock_pool_msg* resultTgStockPoolMsg;
}

- (tg_stock_pool_msg*) defaultInstance;

- (tg_stock_pool_msgBuilder*) clear;
- (tg_stock_pool_msgBuilder*) clone;

- (tg_stock_pool_msg*) build;
- (tg_stock_pool_msg*) buildPartial;

- (tg_stock_pool_msgBuilder*) mergeFrom:(tg_stock_pool_msg*) other;
- (tg_stock_pool_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (tg_stock_pool_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasVersionId;
- (SInt64) versionId;
- (tg_stock_pool_msgBuilder*) setVersionId:(SInt64) value;
- (tg_stock_pool_msgBuilder*) clearVersionId;

- (NSMutableArray *)stocks;
- (tg_stock_att*)stocksAtIndex:(NSUInteger)index;
- (tg_stock_pool_msgBuilder *)addStocks:(tg_stock_att*)value;
- (tg_stock_pool_msgBuilder *)setStocksArray:(NSArray *)array;
- (tg_stock_pool_msgBuilder *)clearStocks;

- (BOOL) hasPosition;
- (Float64) position;
- (tg_stock_pool_msgBuilder*) setPosition:(Float64) value;
- (tg_stock_pool_msgBuilder*) clearPosition;
@end

#define tg_stock_in_pool_notify_msg_date @"date"
#define tg_stock_in_pool_notify_msg_code @"code"
#define tg_stock_in_pool_notify_msg_name @"name"
#define tg_stock_in_pool_notify_msg_low_price @"lowPrice"
#define tg_stock_in_pool_notify_msg_high_price @"highPrice"
#define tg_stock_in_pool_notify_msg_target_price @"targetPrice"
#define tg_stock_in_pool_notify_msg_stop_price @"stopPrice"
@interface tg_stock_in_pool_notify_msg : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasLowPrice_:1;
  BOOL hasHighPrice_:1;
  BOOL hasTargetPrice_:1;
  BOOL hasStopPrice_:1;
  BOOL hasDate_:1;
  BOOL hasCode_:1;
  BOOL hasName_:1;
  Float32 lowPrice;
  Float32 highPrice;
  Float32 targetPrice;
  Float32 stopPrice;
  SInt64 date;
  NSString* code;
  NSString* name;
}
- (BOOL) hasDate;
- (BOOL) hasCode;
- (BOOL) hasName;
- (BOOL) hasLowPrice;
- (BOOL) hasHighPrice;
- (BOOL) hasTargetPrice;
- (BOOL) hasStopPrice;
@property (readonly) SInt64 date;
@property (readonly, strong) NSString* code;
@property (readonly, strong) NSString* name;
@property (readonly) Float32 lowPrice;
@property (readonly) Float32 highPrice;
@property (readonly) Float32 targetPrice;
@property (readonly) Float32 stopPrice;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (tg_stock_in_pool_notify_msgBuilder*) builder;
+ (tg_stock_in_pool_notify_msgBuilder*) builder;
+ (tg_stock_in_pool_notify_msgBuilder*) builderWithPrototype:(tg_stock_in_pool_notify_msg*) prototype;
- (tg_stock_in_pool_notify_msgBuilder*) toBuilder;

+ (tg_stock_in_pool_notify_msg*) parseFromData:(NSData*) data;
+ (tg_stock_in_pool_notify_msg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (tg_stock_in_pool_notify_msg*) parseFromInputStream:(NSInputStream*) input;
+ (tg_stock_in_pool_notify_msg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (tg_stock_in_pool_notify_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (tg_stock_in_pool_notify_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface tg_stock_in_pool_notify_msgBuilder : PBGeneratedMessageBuilder {
@private
  tg_stock_in_pool_notify_msg* resultTgStockInPoolNotifyMsg;
}

- (tg_stock_in_pool_notify_msg*) defaultInstance;

- (tg_stock_in_pool_notify_msgBuilder*) clear;
- (tg_stock_in_pool_notify_msgBuilder*) clone;

- (tg_stock_in_pool_notify_msg*) build;
- (tg_stock_in_pool_notify_msg*) buildPartial;

- (tg_stock_in_pool_notify_msgBuilder*) mergeFrom:(tg_stock_in_pool_notify_msg*) other;
- (tg_stock_in_pool_notify_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (tg_stock_in_pool_notify_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasDate;
- (SInt64) date;
- (tg_stock_in_pool_notify_msgBuilder*) setDate:(SInt64) value;
- (tg_stock_in_pool_notify_msgBuilder*) clearDate;

- (BOOL) hasCode;
- (NSString*) code;
- (tg_stock_in_pool_notify_msgBuilder*) setCode:(NSString*) value;
- (tg_stock_in_pool_notify_msgBuilder*) clearCode;

- (BOOL) hasName;
- (NSString*) name;
- (tg_stock_in_pool_notify_msgBuilder*) setName:(NSString*) value;
- (tg_stock_in_pool_notify_msgBuilder*) clearName;

- (BOOL) hasLowPrice;
- (Float32) lowPrice;
- (tg_stock_in_pool_notify_msgBuilder*) setLowPrice:(Float32) value;
- (tg_stock_in_pool_notify_msgBuilder*) clearLowPrice;

- (BOOL) hasHighPrice;
- (Float32) highPrice;
- (tg_stock_in_pool_notify_msgBuilder*) setHighPrice:(Float32) value;
- (tg_stock_in_pool_notify_msgBuilder*) clearHighPrice;

- (BOOL) hasTargetPrice;
- (Float32) targetPrice;
- (tg_stock_in_pool_notify_msgBuilder*) setTargetPrice:(Float32) value;
- (tg_stock_in_pool_notify_msgBuilder*) clearTargetPrice;

- (BOOL) hasStopPrice;
- (Float32) stopPrice;
- (tg_stock_in_pool_notify_msgBuilder*) setStopPrice:(Float32) value;
- (tg_stock_in_pool_notify_msgBuilder*) clearStopPrice;
@end

#define tg_stock_buy_notify_msg_date @"date"
#define tg_stock_buy_notify_msg_code @"code"
#define tg_stock_buy_notify_msg_name @"name"
#define tg_stock_buy_notify_msg_buy_price @"buyPrice"
#define tg_stock_buy_notify_msg_target_price @"targetPrice"
#define tg_stock_buy_notify_msg_stop_price @"stopPrice"
#define tg_stock_buy_notify_msg_auto_buy @"autoBuy"
@interface tg_stock_buy_notify_msg : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasAutoBuy_:1;
  BOOL hasBuyPrice_:1;
  BOOL hasTargetPrice_:1;
  BOOL hasStopPrice_:1;
  BOOL hasDate_:1;
  BOOL hasCode_:1;
  BOOL hasName_:1;
  BOOL autoBuy_:1;
  Float32 buyPrice;
  Float32 targetPrice;
  Float32 stopPrice;
  SInt64 date;
  NSString* code;
  NSString* name;
}
- (BOOL) hasDate;
- (BOOL) hasCode;
- (BOOL) hasName;
- (BOOL) hasBuyPrice;
- (BOOL) hasTargetPrice;
- (BOOL) hasStopPrice;
- (BOOL) hasAutoBuy;
@property (readonly) SInt64 date;
@property (readonly, strong) NSString* code;
@property (readonly, strong) NSString* name;
@property (readonly) Float32 buyPrice;
@property (readonly) Float32 targetPrice;
@property (readonly) Float32 stopPrice;
- (BOOL) autoBuy;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (tg_stock_buy_notify_msgBuilder*) builder;
+ (tg_stock_buy_notify_msgBuilder*) builder;
+ (tg_stock_buy_notify_msgBuilder*) builderWithPrototype:(tg_stock_buy_notify_msg*) prototype;
- (tg_stock_buy_notify_msgBuilder*) toBuilder;

+ (tg_stock_buy_notify_msg*) parseFromData:(NSData*) data;
+ (tg_stock_buy_notify_msg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (tg_stock_buy_notify_msg*) parseFromInputStream:(NSInputStream*) input;
+ (tg_stock_buy_notify_msg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (tg_stock_buy_notify_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (tg_stock_buy_notify_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface tg_stock_buy_notify_msgBuilder : PBGeneratedMessageBuilder {
@private
  tg_stock_buy_notify_msg* resultTgStockBuyNotifyMsg;
}

- (tg_stock_buy_notify_msg*) defaultInstance;

- (tg_stock_buy_notify_msgBuilder*) clear;
- (tg_stock_buy_notify_msgBuilder*) clone;

- (tg_stock_buy_notify_msg*) build;
- (tg_stock_buy_notify_msg*) buildPartial;

- (tg_stock_buy_notify_msgBuilder*) mergeFrom:(tg_stock_buy_notify_msg*) other;
- (tg_stock_buy_notify_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (tg_stock_buy_notify_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasDate;
- (SInt64) date;
- (tg_stock_buy_notify_msgBuilder*) setDate:(SInt64) value;
- (tg_stock_buy_notify_msgBuilder*) clearDate;

- (BOOL) hasCode;
- (NSString*) code;
- (tg_stock_buy_notify_msgBuilder*) setCode:(NSString*) value;
- (tg_stock_buy_notify_msgBuilder*) clearCode;

- (BOOL) hasName;
- (NSString*) name;
- (tg_stock_buy_notify_msgBuilder*) setName:(NSString*) value;
- (tg_stock_buy_notify_msgBuilder*) clearName;

- (BOOL) hasBuyPrice;
- (Float32) buyPrice;
- (tg_stock_buy_notify_msgBuilder*) setBuyPrice:(Float32) value;
- (tg_stock_buy_notify_msgBuilder*) clearBuyPrice;

- (BOOL) hasTargetPrice;
- (Float32) targetPrice;
- (tg_stock_buy_notify_msgBuilder*) setTargetPrice:(Float32) value;
- (tg_stock_buy_notify_msgBuilder*) clearTargetPrice;

- (BOOL) hasStopPrice;
- (Float32) stopPrice;
- (tg_stock_buy_notify_msgBuilder*) setStopPrice:(Float32) value;
- (tg_stock_buy_notify_msgBuilder*) clearStopPrice;

- (BOOL) hasAutoBuy;
- (BOOL) autoBuy;
- (tg_stock_buy_notify_msgBuilder*) setAutoBuy:(BOOL) value;
- (tg_stock_buy_notify_msgBuilder*) clearAutoBuy;
@end

#define tg_stock_out_pool_notify_msg_date @"date"
#define tg_stock_out_pool_notify_msg_code @"code"
#define tg_stock_out_pool_notify_msg_name @"name"
#define tg_stock_out_pool_notify_msg_desc @"desc"
@interface tg_stock_out_pool_notify_msg : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasDate_:1;
  BOOL hasCode_:1;
  BOOL hasName_:1;
  BOOL hasDesc_:1;
  SInt64 date;
  NSString* code;
  NSString* name;
  NSString* desc;
}
- (BOOL) hasDate;
- (BOOL) hasCode;
- (BOOL) hasName;
- (BOOL) hasDesc;
@property (readonly) SInt64 date;
@property (readonly, strong) NSString* code;
@property (readonly, strong) NSString* name;
@property (readonly, strong) NSString* desc;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (tg_stock_out_pool_notify_msgBuilder*) builder;
+ (tg_stock_out_pool_notify_msgBuilder*) builder;
+ (tg_stock_out_pool_notify_msgBuilder*) builderWithPrototype:(tg_stock_out_pool_notify_msg*) prototype;
- (tg_stock_out_pool_notify_msgBuilder*) toBuilder;

+ (tg_stock_out_pool_notify_msg*) parseFromData:(NSData*) data;
+ (tg_stock_out_pool_notify_msg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (tg_stock_out_pool_notify_msg*) parseFromInputStream:(NSInputStream*) input;
+ (tg_stock_out_pool_notify_msg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (tg_stock_out_pool_notify_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (tg_stock_out_pool_notify_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface tg_stock_out_pool_notify_msgBuilder : PBGeneratedMessageBuilder {
@private
  tg_stock_out_pool_notify_msg* resultTgStockOutPoolNotifyMsg;
}

- (tg_stock_out_pool_notify_msg*) defaultInstance;

- (tg_stock_out_pool_notify_msgBuilder*) clear;
- (tg_stock_out_pool_notify_msgBuilder*) clone;

- (tg_stock_out_pool_notify_msg*) build;
- (tg_stock_out_pool_notify_msg*) buildPartial;

- (tg_stock_out_pool_notify_msgBuilder*) mergeFrom:(tg_stock_out_pool_notify_msg*) other;
- (tg_stock_out_pool_notify_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (tg_stock_out_pool_notify_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasDate;
- (SInt64) date;
- (tg_stock_out_pool_notify_msgBuilder*) setDate:(SInt64) value;
- (tg_stock_out_pool_notify_msgBuilder*) clearDate;

- (BOOL) hasCode;
- (NSString*) code;
- (tg_stock_out_pool_notify_msgBuilder*) setCode:(NSString*) value;
- (tg_stock_out_pool_notify_msgBuilder*) clearCode;

- (BOOL) hasName;
- (NSString*) name;
- (tg_stock_out_pool_notify_msgBuilder*) setName:(NSString*) value;
- (tg_stock_out_pool_notify_msgBuilder*) clearName;

- (BOOL) hasDesc;
- (NSString*) desc;
- (tg_stock_out_pool_notify_msgBuilder*) setDesc:(NSString*) value;
- (tg_stock_out_pool_notify_msgBuilder*) clearDesc;
@end

#define tg_stock_new_target_notify_msg_date @"date"
#define tg_stock_new_target_notify_msg_code @"code"
#define tg_stock_new_target_notify_msg_old_target @"oldTarget"
#define tg_stock_new_target_notify_msg_new_target @"newTarget"
@interface tg_stock_new_target_notify_msg : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasOldTarget_:1;
  BOOL hasNewTarget_:1;
  BOOL hasDate_:1;
  BOOL hasCode_:1;
  Float32 oldTarget;
  Float32 newTarget;
  SInt64 date;
  NSString* code;
}
- (BOOL) hasDate;
- (BOOL) hasCode;
- (BOOL) hasOldTarget;
- (BOOL) hasNewTarget;
@property (readonly) SInt64 date;
@property (readonly, strong) NSString* code;
@property (readonly) Float32 oldTarget;
@property (readonly) Float32 newTarget;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (tg_stock_new_target_notify_msgBuilder*) builder;
+ (tg_stock_new_target_notify_msgBuilder*) builder;
+ (tg_stock_new_target_notify_msgBuilder*) builderWithPrototype:(tg_stock_new_target_notify_msg*) prototype;
- (tg_stock_new_target_notify_msgBuilder*) toBuilder;

+ (tg_stock_new_target_notify_msg*) parseFromData:(NSData*) data;
+ (tg_stock_new_target_notify_msg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (tg_stock_new_target_notify_msg*) parseFromInputStream:(NSInputStream*) input;
+ (tg_stock_new_target_notify_msg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (tg_stock_new_target_notify_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (tg_stock_new_target_notify_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface tg_stock_new_target_notify_msgBuilder : PBGeneratedMessageBuilder {
@private
  tg_stock_new_target_notify_msg* resultTgStockNewTargetNotifyMsg;
}

- (tg_stock_new_target_notify_msg*) defaultInstance;

- (tg_stock_new_target_notify_msgBuilder*) clear;
- (tg_stock_new_target_notify_msgBuilder*) clone;

- (tg_stock_new_target_notify_msg*) build;
- (tg_stock_new_target_notify_msg*) buildPartial;

- (tg_stock_new_target_notify_msgBuilder*) mergeFrom:(tg_stock_new_target_notify_msg*) other;
- (tg_stock_new_target_notify_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (tg_stock_new_target_notify_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasDate;
- (SInt64) date;
- (tg_stock_new_target_notify_msgBuilder*) setDate:(SInt64) value;
- (tg_stock_new_target_notify_msgBuilder*) clearDate;

- (BOOL) hasCode;
- (NSString*) code;
- (tg_stock_new_target_notify_msgBuilder*) setCode:(NSString*) value;
- (tg_stock_new_target_notify_msgBuilder*) clearCode;

- (BOOL) hasOldTarget;
- (Float32) oldTarget;
- (tg_stock_new_target_notify_msgBuilder*) setOldTarget:(Float32) value;
- (tg_stock_new_target_notify_msgBuilder*) clearOldTarget;

- (BOOL) hasNewTarget;
- (Float32) newTarget;
- (tg_stock_new_target_notify_msgBuilder*) setNewTarget:(Float32) value;
- (tg_stock_new_target_notify_msgBuilder*) clearNewTarget;
@end

#define tg_stock_new_stop_notify_msg_date @"date"
#define tg_stock_new_stop_notify_msg_code @"code"
#define tg_stock_new_stop_notify_msg_old_stop @"oldStop"
#define tg_stock_new_stop_notify_msg_new_stop @"newStop"
@interface tg_stock_new_stop_notify_msg : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasOldStop_:1;
  BOOL hasNewStop_:1;
  BOOL hasDate_:1;
  BOOL hasCode_:1;
  Float32 oldStop;
  Float32 newStop;
  SInt64 date;
  NSString* code;
}
- (BOOL) hasDate;
- (BOOL) hasCode;
- (BOOL) hasOldStop;
- (BOOL) hasNewStop;
@property (readonly) SInt64 date;
@property (readonly, strong) NSString* code;
@property (readonly) Float32 oldStop;
@property (readonly) Float32 newStop;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (tg_stock_new_stop_notify_msgBuilder*) builder;
+ (tg_stock_new_stop_notify_msgBuilder*) builder;
+ (tg_stock_new_stop_notify_msgBuilder*) builderWithPrototype:(tg_stock_new_stop_notify_msg*) prototype;
- (tg_stock_new_stop_notify_msgBuilder*) toBuilder;

+ (tg_stock_new_stop_notify_msg*) parseFromData:(NSData*) data;
+ (tg_stock_new_stop_notify_msg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (tg_stock_new_stop_notify_msg*) parseFromInputStream:(NSInputStream*) input;
+ (tg_stock_new_stop_notify_msg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (tg_stock_new_stop_notify_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (tg_stock_new_stop_notify_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface tg_stock_new_stop_notify_msgBuilder : PBGeneratedMessageBuilder {
@private
  tg_stock_new_stop_notify_msg* resultTgStockNewStopNotifyMsg;
}

- (tg_stock_new_stop_notify_msg*) defaultInstance;

- (tg_stock_new_stop_notify_msgBuilder*) clear;
- (tg_stock_new_stop_notify_msgBuilder*) clone;

- (tg_stock_new_stop_notify_msg*) build;
- (tg_stock_new_stop_notify_msg*) buildPartial;

- (tg_stock_new_stop_notify_msgBuilder*) mergeFrom:(tg_stock_new_stop_notify_msg*) other;
- (tg_stock_new_stop_notify_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (tg_stock_new_stop_notify_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasDate;
- (SInt64) date;
- (tg_stock_new_stop_notify_msgBuilder*) setDate:(SInt64) value;
- (tg_stock_new_stop_notify_msgBuilder*) clearDate;

- (BOOL) hasCode;
- (NSString*) code;
- (tg_stock_new_stop_notify_msgBuilder*) setCode:(NSString*) value;
- (tg_stock_new_stop_notify_msgBuilder*) clearCode;

- (BOOL) hasOldStop;
- (Float32) oldStop;
- (tg_stock_new_stop_notify_msgBuilder*) setOldStop:(Float32) value;
- (tg_stock_new_stop_notify_msgBuilder*) clearOldStop;

- (BOOL) hasNewStop;
- (Float32) newStop;
- (tg_stock_new_stop_notify_msgBuilder*) setNewStop:(Float32) value;
- (tg_stock_new_stop_notify_msgBuilder*) clearNewStop;
@end

#define tg_stock_profit_notify_msg_date @"date"
#define tg_stock_profit_notify_msg_code @"code"
#define tg_stock_profit_notify_msg_target_price @"targetPrice"
#define tg_stock_profit_notify_msg_sell_price @"sellPrice"
#define tg_stock_profit_notify_msg_system_auto @"systemAuto"
#define tg_stock_profit_notify_msg_desc @"desc"
@interface tg_stock_profit_notify_msg : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasSystemAuto_:1;
  BOOL hasTargetPrice_:1;
  BOOL hasSellPrice_:1;
  BOOL hasDate_:1;
  BOOL hasCode_:1;
  BOOL hasDesc_:1;
  BOOL systemAuto_:1;
  Float32 targetPrice;
  Float32 sellPrice;
  SInt64 date;
  NSString* code;
  NSString* desc;
}
- (BOOL) hasDate;
- (BOOL) hasCode;
- (BOOL) hasTargetPrice;
- (BOOL) hasSellPrice;
- (BOOL) hasSystemAuto;
- (BOOL) hasDesc;
@property (readonly) SInt64 date;
@property (readonly, strong) NSString* code;
@property (readonly) Float32 targetPrice;
@property (readonly) Float32 sellPrice;
- (BOOL) systemAuto;
@property (readonly, strong) NSString* desc;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (tg_stock_profit_notify_msgBuilder*) builder;
+ (tg_stock_profit_notify_msgBuilder*) builder;
+ (tg_stock_profit_notify_msgBuilder*) builderWithPrototype:(tg_stock_profit_notify_msg*) prototype;
- (tg_stock_profit_notify_msgBuilder*) toBuilder;

+ (tg_stock_profit_notify_msg*) parseFromData:(NSData*) data;
+ (tg_stock_profit_notify_msg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (tg_stock_profit_notify_msg*) parseFromInputStream:(NSInputStream*) input;
+ (tg_stock_profit_notify_msg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (tg_stock_profit_notify_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (tg_stock_profit_notify_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface tg_stock_profit_notify_msgBuilder : PBGeneratedMessageBuilder {
@private
  tg_stock_profit_notify_msg* resultTgStockProfitNotifyMsg;
}

- (tg_stock_profit_notify_msg*) defaultInstance;

- (tg_stock_profit_notify_msgBuilder*) clear;
- (tg_stock_profit_notify_msgBuilder*) clone;

- (tg_stock_profit_notify_msg*) build;
- (tg_stock_profit_notify_msg*) buildPartial;

- (tg_stock_profit_notify_msgBuilder*) mergeFrom:(tg_stock_profit_notify_msg*) other;
- (tg_stock_profit_notify_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (tg_stock_profit_notify_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasDate;
- (SInt64) date;
- (tg_stock_profit_notify_msgBuilder*) setDate:(SInt64) value;
- (tg_stock_profit_notify_msgBuilder*) clearDate;

- (BOOL) hasCode;
- (NSString*) code;
- (tg_stock_profit_notify_msgBuilder*) setCode:(NSString*) value;
- (tg_stock_profit_notify_msgBuilder*) clearCode;

- (BOOL) hasTargetPrice;
- (Float32) targetPrice;
- (tg_stock_profit_notify_msgBuilder*) setTargetPrice:(Float32) value;
- (tg_stock_profit_notify_msgBuilder*) clearTargetPrice;

- (BOOL) hasSellPrice;
- (Float32) sellPrice;
- (tg_stock_profit_notify_msgBuilder*) setSellPrice:(Float32) value;
- (tg_stock_profit_notify_msgBuilder*) clearSellPrice;

- (BOOL) hasSystemAuto;
- (BOOL) systemAuto;
- (tg_stock_profit_notify_msgBuilder*) setSystemAuto:(BOOL) value;
- (tg_stock_profit_notify_msgBuilder*) clearSystemAuto;

- (BOOL) hasDesc;
- (NSString*) desc;
- (tg_stock_profit_notify_msgBuilder*) setDesc:(NSString*) value;
- (tg_stock_profit_notify_msgBuilder*) clearDesc;
@end

#define tg_stock_stop_notify_msg_date @"date"
#define tg_stock_stop_notify_msg_code @"code"
#define tg_stock_stop_notify_msg_stop_price @"stopPrice"
#define tg_stock_stop_notify_msg_sell_price @"sellPrice"
#define tg_stock_stop_notify_msg_system_auto @"systemAuto"
#define tg_stock_stop_notify_msg_desc @"desc"
@interface tg_stock_stop_notify_msg : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasSystemAuto_:1;
  BOOL hasStopPrice_:1;
  BOOL hasSellPrice_:1;
  BOOL hasDate_:1;
  BOOL hasCode_:1;
  BOOL hasDesc_:1;
  BOOL systemAuto_:1;
  Float32 stopPrice;
  Float32 sellPrice;
  SInt64 date;
  NSString* code;
  NSString* desc;
}
- (BOOL) hasDate;
- (BOOL) hasCode;
- (BOOL) hasStopPrice;
- (BOOL) hasSellPrice;
- (BOOL) hasSystemAuto;
- (BOOL) hasDesc;
@property (readonly) SInt64 date;
@property (readonly, strong) NSString* code;
@property (readonly) Float32 stopPrice;
@property (readonly) Float32 sellPrice;
- (BOOL) systemAuto;
@property (readonly, strong) NSString* desc;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (tg_stock_stop_notify_msgBuilder*) builder;
+ (tg_stock_stop_notify_msgBuilder*) builder;
+ (tg_stock_stop_notify_msgBuilder*) builderWithPrototype:(tg_stock_stop_notify_msg*) prototype;
- (tg_stock_stop_notify_msgBuilder*) toBuilder;

+ (tg_stock_stop_notify_msg*) parseFromData:(NSData*) data;
+ (tg_stock_stop_notify_msg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (tg_stock_stop_notify_msg*) parseFromInputStream:(NSInputStream*) input;
+ (tg_stock_stop_notify_msg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (tg_stock_stop_notify_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (tg_stock_stop_notify_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface tg_stock_stop_notify_msgBuilder : PBGeneratedMessageBuilder {
@private
  tg_stock_stop_notify_msg* resultTgStockStopNotifyMsg;
}

- (tg_stock_stop_notify_msg*) defaultInstance;

- (tg_stock_stop_notify_msgBuilder*) clear;
- (tg_stock_stop_notify_msgBuilder*) clone;

- (tg_stock_stop_notify_msg*) build;
- (tg_stock_stop_notify_msg*) buildPartial;

- (tg_stock_stop_notify_msgBuilder*) mergeFrom:(tg_stock_stop_notify_msg*) other;
- (tg_stock_stop_notify_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (tg_stock_stop_notify_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasDate;
- (SInt64) date;
- (tg_stock_stop_notify_msgBuilder*) setDate:(SInt64) value;
- (tg_stock_stop_notify_msgBuilder*) clearDate;

- (BOOL) hasCode;
- (NSString*) code;
- (tg_stock_stop_notify_msgBuilder*) setCode:(NSString*) value;
- (tg_stock_stop_notify_msgBuilder*) clearCode;

- (BOOL) hasStopPrice;
- (Float32) stopPrice;
- (tg_stock_stop_notify_msgBuilder*) setStopPrice:(Float32) value;
- (tg_stock_stop_notify_msgBuilder*) clearStopPrice;

- (BOOL) hasSellPrice;
- (Float32) sellPrice;
- (tg_stock_stop_notify_msgBuilder*) setSellPrice:(Float32) value;
- (tg_stock_stop_notify_msgBuilder*) clearSellPrice;

- (BOOL) hasSystemAuto;
- (BOOL) systemAuto;
- (tg_stock_stop_notify_msgBuilder*) setSystemAuto:(BOOL) value;
- (tg_stock_stop_notify_msgBuilder*) clearSystemAuto;

- (BOOL) hasDesc;
- (NSString*) desc;
- (tg_stock_stop_notify_msgBuilder*) setDesc:(NSString*) value;
- (tg_stock_stop_notify_msgBuilder*) clearDesc;
@end

#define tg_focus_news_notify_msg_date @"date"
#define tg_focus_news_notify_msg_title @"title"
#define tg_focus_news_notify_msg_content @"content"
#define tg_focus_news_notify_msg_url @"url"
@interface tg_focus_news_notify_msg : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasDate_:1;
  BOOL hasTitle_:1;
  BOOL hasContent_:1;
  BOOL hasUrl_:1;
  SInt64 date;
  NSString* title;
  NSString* content;
  NSString* url;
}
- (BOOL) hasDate;
- (BOOL) hasTitle;
- (BOOL) hasContent;
- (BOOL) hasUrl;
@property (readonly) SInt64 date;
@property (readonly, strong) NSString* title;
@property (readonly, strong) NSString* content;
@property (readonly, strong) NSString* url;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (tg_focus_news_notify_msgBuilder*) builder;
+ (tg_focus_news_notify_msgBuilder*) builder;
+ (tg_focus_news_notify_msgBuilder*) builderWithPrototype:(tg_focus_news_notify_msg*) prototype;
- (tg_focus_news_notify_msgBuilder*) toBuilder;

+ (tg_focus_news_notify_msg*) parseFromData:(NSData*) data;
+ (tg_focus_news_notify_msg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (tg_focus_news_notify_msg*) parseFromInputStream:(NSInputStream*) input;
+ (tg_focus_news_notify_msg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (tg_focus_news_notify_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (tg_focus_news_notify_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface tg_focus_news_notify_msgBuilder : PBGeneratedMessageBuilder {
@private
  tg_focus_news_notify_msg* resultTgFocusNewsNotifyMsg;
}

- (tg_focus_news_notify_msg*) defaultInstance;

- (tg_focus_news_notify_msgBuilder*) clear;
- (tg_focus_news_notify_msgBuilder*) clone;

- (tg_focus_news_notify_msg*) build;
- (tg_focus_news_notify_msg*) buildPartial;

- (tg_focus_news_notify_msgBuilder*) mergeFrom:(tg_focus_news_notify_msg*) other;
- (tg_focus_news_notify_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (tg_focus_news_notify_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasDate;
- (SInt64) date;
- (tg_focus_news_notify_msgBuilder*) setDate:(SInt64) value;
- (tg_focus_news_notify_msgBuilder*) clearDate;

- (BOOL) hasTitle;
- (NSString*) title;
- (tg_focus_news_notify_msgBuilder*) setTitle:(NSString*) value;
- (tg_focus_news_notify_msgBuilder*) clearTitle;

- (BOOL) hasContent;
- (NSString*) content;
- (tg_focus_news_notify_msgBuilder*) setContent:(NSString*) value;
- (tg_focus_news_notify_msgBuilder*) clearContent;

- (BOOL) hasUrl;
- (NSString*) url;
- (tg_focus_news_notify_msgBuilder*) setUrl:(NSString*) value;
- (tg_focus_news_notify_msgBuilder*) clearUrl;
@end

#define tg_trailer_notify_msg_date @"date"
#define tg_trailer_notify_msg_title @"title"
#define tg_trailer_notify_msg_content @"content"
#define tg_trailer_notify_msg_url @"url"
@interface tg_trailer_notify_msg : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasDate_:1;
  BOOL hasTitle_:1;
  BOOL hasContent_:1;
  BOOL hasUrl_:1;
  SInt64 date;
  NSString* title;
  NSString* content;
  NSString* url;
}
- (BOOL) hasDate;
- (BOOL) hasTitle;
- (BOOL) hasContent;
- (BOOL) hasUrl;
@property (readonly) SInt64 date;
@property (readonly, strong) NSString* title;
@property (readonly, strong) NSString* content;
@property (readonly, strong) NSString* url;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (tg_trailer_notify_msgBuilder*) builder;
+ (tg_trailer_notify_msgBuilder*) builder;
+ (tg_trailer_notify_msgBuilder*) builderWithPrototype:(tg_trailer_notify_msg*) prototype;
- (tg_trailer_notify_msgBuilder*) toBuilder;

+ (tg_trailer_notify_msg*) parseFromData:(NSData*) data;
+ (tg_trailer_notify_msg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (tg_trailer_notify_msg*) parseFromInputStream:(NSInputStream*) input;
+ (tg_trailer_notify_msg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (tg_trailer_notify_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (tg_trailer_notify_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface tg_trailer_notify_msgBuilder : PBGeneratedMessageBuilder {
@private
  tg_trailer_notify_msg* resultTgTrailerNotifyMsg;
}

- (tg_trailer_notify_msg*) defaultInstance;

- (tg_trailer_notify_msgBuilder*) clear;
- (tg_trailer_notify_msgBuilder*) clone;

- (tg_trailer_notify_msg*) build;
- (tg_trailer_notify_msg*) buildPartial;

- (tg_trailer_notify_msgBuilder*) mergeFrom:(tg_trailer_notify_msg*) other;
- (tg_trailer_notify_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (tg_trailer_notify_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasDate;
- (SInt64) date;
- (tg_trailer_notify_msgBuilder*) setDate:(SInt64) value;
- (tg_trailer_notify_msgBuilder*) clearDate;

- (BOOL) hasTitle;
- (NSString*) title;
- (tg_trailer_notify_msgBuilder*) setTitle:(NSString*) value;
- (tg_trailer_notify_msgBuilder*) clearTitle;

- (BOOL) hasContent;
- (NSString*) content;
- (tg_trailer_notify_msgBuilder*) setContent:(NSString*) value;
- (tg_trailer_notify_msgBuilder*) clearContent;

- (BOOL) hasUrl;
- (NSString*) url;
- (tg_trailer_notify_msgBuilder*) setUrl:(NSString*) value;
- (tg_trailer_notify_msgBuilder*) clearUrl;
@end

#define tg_req_msg_box_msg_pid @"pid"
#define tg_req_msg_box_msg_last_seq @"lastSeq"
@interface tg_req_msg_box_msg : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasLastSeq_:1;
  BOOL hasPid_:1;
  SInt64 lastSeq;
  SInt32 pid;
}
- (BOOL) hasPid;
- (BOOL) hasLastSeq;
@property (readonly) SInt32 pid;
@property (readonly) SInt64 lastSeq;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (tg_req_msg_box_msgBuilder*) builder;
+ (tg_req_msg_box_msgBuilder*) builder;
+ (tg_req_msg_box_msgBuilder*) builderWithPrototype:(tg_req_msg_box_msg*) prototype;
- (tg_req_msg_box_msgBuilder*) toBuilder;

+ (tg_req_msg_box_msg*) parseFromData:(NSData*) data;
+ (tg_req_msg_box_msg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (tg_req_msg_box_msg*) parseFromInputStream:(NSInputStream*) input;
+ (tg_req_msg_box_msg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (tg_req_msg_box_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (tg_req_msg_box_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface tg_req_msg_box_msgBuilder : PBGeneratedMessageBuilder {
@private
  tg_req_msg_box_msg* resultTgReqMsgBoxMsg;
}

- (tg_req_msg_box_msg*) defaultInstance;

- (tg_req_msg_box_msgBuilder*) clear;
- (tg_req_msg_box_msgBuilder*) clone;

- (tg_req_msg_box_msg*) build;
- (tg_req_msg_box_msg*) buildPartial;

- (tg_req_msg_box_msgBuilder*) mergeFrom:(tg_req_msg_box_msg*) other;
- (tg_req_msg_box_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (tg_req_msg_box_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPid;
- (SInt32) pid;
- (tg_req_msg_box_msgBuilder*) setPid:(SInt32) value;
- (tg_req_msg_box_msgBuilder*) clearPid;

- (BOOL) hasLastSeq;
- (SInt64) lastSeq;
- (tg_req_msg_box_msgBuilder*) setLastSeq:(SInt64) value;
- (tg_req_msg_box_msgBuilder*) clearLastSeq;
@end

#define tg_msg_box_combo_msg_msgs @"msgs"
@interface tg_msg_box_combo_msg : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  NSMutableArray * msgsArray;
}
@property (readonly, strong) NSArray * msgs;
- (tg_msg_box_combo_msgtg_msg_node*)msgsAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (tg_msg_box_combo_msgBuilder*) builder;
+ (tg_msg_box_combo_msgBuilder*) builder;
+ (tg_msg_box_combo_msgBuilder*) builderWithPrototype:(tg_msg_box_combo_msg*) prototype;
- (tg_msg_box_combo_msgBuilder*) toBuilder;

+ (tg_msg_box_combo_msg*) parseFromData:(NSData*) data;
+ (tg_msg_box_combo_msg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (tg_msg_box_combo_msg*) parseFromInputStream:(NSInputStream*) input;
+ (tg_msg_box_combo_msg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (tg_msg_box_combo_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (tg_msg_box_combo_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

#define tg_msg_node_type @"type"
#define tg_msg_node_sub_msg @"subMsg"
#define tg_msg_node_msg_seq @"msgSeq"
@interface tg_msg_box_combo_msgtg_msg_node : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasMsgSeq_:1;
  BOOL hasSubMsg_:1;
  BOOL hasType_:1;
  SInt64 msgSeq;
  NSData* subMsg;
  eum_nofity_type type;
}
- (BOOL) hasType;
- (BOOL) hasSubMsg;
- (BOOL) hasMsgSeq;
@property (readonly) eum_nofity_type type;
@property (readonly, strong) NSData* subMsg;
@property (readonly) SInt64 msgSeq;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (tg_msg_box_combo_msgtg_msg_nodeBuilder*) builder;
+ (tg_msg_box_combo_msgtg_msg_nodeBuilder*) builder;
+ (tg_msg_box_combo_msgtg_msg_nodeBuilder*) builderWithPrototype:(tg_msg_box_combo_msgtg_msg_node*) prototype;
- (tg_msg_box_combo_msgtg_msg_nodeBuilder*) toBuilder;

+ (tg_msg_box_combo_msgtg_msg_node*) parseFromData:(NSData*) data;
+ (tg_msg_box_combo_msgtg_msg_node*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (tg_msg_box_combo_msgtg_msg_node*) parseFromInputStream:(NSInputStream*) input;
+ (tg_msg_box_combo_msgtg_msg_node*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (tg_msg_box_combo_msgtg_msg_node*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (tg_msg_box_combo_msgtg_msg_node*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface tg_msg_box_combo_msgtg_msg_nodeBuilder : PBGeneratedMessageBuilder {
@private
  tg_msg_box_combo_msgtg_msg_node* resultTgMsgNode;
}

- (tg_msg_box_combo_msgtg_msg_node*) defaultInstance;

- (tg_msg_box_combo_msgtg_msg_nodeBuilder*) clear;
- (tg_msg_box_combo_msgtg_msg_nodeBuilder*) clone;

- (tg_msg_box_combo_msgtg_msg_node*) build;
- (tg_msg_box_combo_msgtg_msg_node*) buildPartial;

- (tg_msg_box_combo_msgtg_msg_nodeBuilder*) mergeFrom:(tg_msg_box_combo_msgtg_msg_node*) other;
- (tg_msg_box_combo_msgtg_msg_nodeBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (tg_msg_box_combo_msgtg_msg_nodeBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasType;
- (eum_nofity_type) type;
- (tg_msg_box_combo_msgtg_msg_nodeBuilder*) setType:(eum_nofity_type) value;
- (tg_msg_box_combo_msgtg_msg_nodeBuilder*) clearType;

- (BOOL) hasSubMsg;
- (NSData*) subMsg;
- (tg_msg_box_combo_msgtg_msg_nodeBuilder*) setSubMsg:(NSData*) value;
- (tg_msg_box_combo_msgtg_msg_nodeBuilder*) clearSubMsg;

- (BOOL) hasMsgSeq;
- (SInt64) msgSeq;
- (tg_msg_box_combo_msgtg_msg_nodeBuilder*) setMsgSeq:(SInt64) value;
- (tg_msg_box_combo_msgtg_msg_nodeBuilder*) clearMsgSeq;
@end

@interface tg_msg_box_combo_msgBuilder : PBGeneratedMessageBuilder {
@private
  tg_msg_box_combo_msg* resultTgMsgBoxComboMsg;
}

- (tg_msg_box_combo_msg*) defaultInstance;

- (tg_msg_box_combo_msgBuilder*) clear;
- (tg_msg_box_combo_msgBuilder*) clone;

- (tg_msg_box_combo_msg*) build;
- (tg_msg_box_combo_msg*) buildPartial;

- (tg_msg_box_combo_msgBuilder*) mergeFrom:(tg_msg_box_combo_msg*) other;
- (tg_msg_box_combo_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (tg_msg_box_combo_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)msgs;
- (tg_msg_box_combo_msgtg_msg_node*)msgsAtIndex:(NSUInteger)index;
- (tg_msg_box_combo_msgBuilder *)addMsgs:(tg_msg_box_combo_msgtg_msg_node*)value;
- (tg_msg_box_combo_msgBuilder *)setMsgsArray:(NSArray *)array;
- (tg_msg_box_combo_msgBuilder *)clearMsgs;
@end


// @@protoc_insertion_point(global_scope)
