// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

#import "Common.pb.h"
// @@protoc_insertion_point(imports)

@class auth_ctx_msg;
@class auth_ctx_msgBuilder;
@class client_login_msg;
@class client_login_msgBuilder;
@class client_login_result_msg;
@class client_login_result_msgBuilder;
@class combo_private_msg;
@class combo_private_msgBuilder;
@class common_reply_error_msg;
@class common_reply_error_msgBuilder;
@class common_update_notice_msg;
@class common_update_notice_msgBuilder;
@class count_offset_selector;
@class count_offset_selectorBuilder;
@class data_selector;
@class data_selectorBuilder;
@class delete_warning_config_form_code_msg;
@class delete_warning_config_form_code_msgBuilder;
@class delete_warning_config_result_form_code_msg;
@class delete_warning_config_result_form_code_msgBuilder;
@class ext_key_info;
@class ext_key_infoBuilder;
@class get_warning_record_from_uid_msg;
@class get_warning_record_from_uid_msgBuilder;
@class get_warning_record_from_uid_result_msg;
@class get_warning_record_from_uid_result_msgBuilder;
@class load_dector_msg;
@class load_dector_msgBuilder;
@class notify_ack_msg;
@class notify_ack_msgBuilder;
@class push_notify_msg;
@class push_notify_msgBuilder;
@class rpc_msg_root;
@class rpc_msg_rootBuilder;
@class server_login_msg;
@class server_login_msgBuilder;
@class server_login_result_msg;
@class server_login_result_msgBuilder;
@class set_warning_config_msg;
@class set_warning_config_msgBuilder;
@class set_warning_config_result_msg;
@class set_warning_config_result_msgBuilder;
@class subcribe_msg;
@class subcribe_msgBuilder;
@class sync_notify_msg;
@class sync_notify_msgBuilder;
@class time_offset_selector;
@class time_offset_selectorBuilder;
@class time_range_selector;
@class time_range_selectorBuilder;
@class user_warning_stock_status;
@class user_warning_stock_statusBuilder;
@class warning_config_data;
@class warning_config_dataBuilder;
@class warning_config_msg;
@class warning_config_msgBuilder;
@class warning_config_result_msg;
@class warning_config_result_msgBuilder;
@class warning_record;
@class warning_recordBuilder;
@class warning_recordwarning_msg_node;
@class warning_recordwarning_msg_nodeBuilder;
@class warning_stock_value;
@class warning_stock_valueBuilder;
@class warning_user_all_stock_status_msg;
@class warning_user_all_stock_status_msgBuilder;
@class warning_user_all_stock_status_result_msg;
@class warning_user_all_stock_status_result_msgBuilder;


typedef NS_ENUM(SInt32, enum_warning_type) {
  enum_warning_typeBeginWarningTypeEnum = 0,
  enum_warning_typeWarningPriceHigh = 1,
  enum_warning_typeWarningPriceLow = 2,
  enum_warning_typeWarningRisePercentage = 3,
  enum_warning_typeWarningDropPercentage = 4,
  enum_warning_typeEndWarningTypeEnum = 5,
};

BOOL enum_warning_typeIsValidValue(enum_warning_type value);
NSString *NSStringFromenum_warning_type(enum_warning_type value);


@interface WarningRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define warning_config_data_type @"type"
#define warning_config_data_value @"value"
#define warning_config_data_status @"status"
@interface warning_config_data : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasValue_:1;
  BOOL hasStatus_:1;
  BOOL hasType_:1;
  Float32 value;
  UInt32 status;
  enum_warning_type type;
}
- (BOOL) hasType;
- (BOOL) hasValue;
- (BOOL) hasStatus;
@property (readonly) enum_warning_type type;
@property (readonly) Float32 value;
@property (readonly) UInt32 status;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (warning_config_dataBuilder*) builder;
+ (warning_config_dataBuilder*) builder;
+ (warning_config_dataBuilder*) builderWithPrototype:(warning_config_data*) prototype;
- (warning_config_dataBuilder*) toBuilder;

+ (warning_config_data*) parseFromData:(NSData*) data;
+ (warning_config_data*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (warning_config_data*) parseFromInputStream:(NSInputStream*) input;
+ (warning_config_data*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (warning_config_data*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (warning_config_data*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface warning_config_dataBuilder : PBGeneratedMessageBuilder {
@private
  warning_config_data* resultWarningConfigData;
}

- (warning_config_data*) defaultInstance;

- (warning_config_dataBuilder*) clear;
- (warning_config_dataBuilder*) clone;

- (warning_config_data*) build;
- (warning_config_data*) buildPartial;

- (warning_config_dataBuilder*) mergeFrom:(warning_config_data*) other;
- (warning_config_dataBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (warning_config_dataBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasType;
- (enum_warning_type) type;
- (warning_config_dataBuilder*) setType:(enum_warning_type) value;
- (warning_config_dataBuilder*) clearType;

- (BOOL) hasValue;
- (Float32) value;
- (warning_config_dataBuilder*) setValue:(Float32) value;
- (warning_config_dataBuilder*) clearValue;

- (BOOL) hasStatus;
- (UInt32) status;
- (warning_config_dataBuilder*) setStatus:(UInt32) value;
- (warning_config_dataBuilder*) clearStatus;
@end

#define user_warning_stock_status_stock_code @"stockCode"
#define user_warning_stock_status_stock_name @"stockName"
#define user_warning_stock_status_status @"status"
@interface user_warning_stock_status : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasStatus_:1;
  BOOL hasStockCode_:1;
  BOOL hasStockName_:1;
  BOOL status_:1;
  NSString* stockCode;
  NSString* stockName;
}
- (BOOL) hasStockCode;
- (BOOL) hasStockName;
- (BOOL) hasStatus;
@property (readonly, strong) NSString* stockCode;
@property (readonly, strong) NSString* stockName;
- (BOOL) status;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (user_warning_stock_statusBuilder*) builder;
+ (user_warning_stock_statusBuilder*) builder;
+ (user_warning_stock_statusBuilder*) builderWithPrototype:(user_warning_stock_status*) prototype;
- (user_warning_stock_statusBuilder*) toBuilder;

+ (user_warning_stock_status*) parseFromData:(NSData*) data;
+ (user_warning_stock_status*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (user_warning_stock_status*) parseFromInputStream:(NSInputStream*) input;
+ (user_warning_stock_status*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (user_warning_stock_status*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (user_warning_stock_status*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface user_warning_stock_statusBuilder : PBGeneratedMessageBuilder {
@private
  user_warning_stock_status* resultUserWarningStockStatus;
}

- (user_warning_stock_status*) defaultInstance;

- (user_warning_stock_statusBuilder*) clear;
- (user_warning_stock_statusBuilder*) clone;

- (user_warning_stock_status*) build;
- (user_warning_stock_status*) buildPartial;

- (user_warning_stock_statusBuilder*) mergeFrom:(user_warning_stock_status*) other;
- (user_warning_stock_statusBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (user_warning_stock_statusBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStockCode;
- (NSString*) stockCode;
- (user_warning_stock_statusBuilder*) setStockCode:(NSString*) value;
- (user_warning_stock_statusBuilder*) clearStockCode;

- (BOOL) hasStockName;
- (NSString*) stockName;
- (user_warning_stock_statusBuilder*) setStockName:(NSString*) value;
- (user_warning_stock_statusBuilder*) clearStockName;

- (BOOL) hasStatus;
- (BOOL) status;
- (user_warning_stock_statusBuilder*) setStatus:(BOOL) value;
- (user_warning_stock_statusBuilder*) clearStatus;
@end

#define warning_config_msg_uid @"uid"
#define warning_config_msg_stock_code @"stockCode"
@interface warning_config_msg : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasStockCode_:1;
  BOOL hasUid_:1;
  NSString* stockCode;
  UInt32 uid;
}
- (BOOL) hasUid;
- (BOOL) hasStockCode;
@property (readonly) UInt32 uid;
@property (readonly, strong) NSString* stockCode;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (warning_config_msgBuilder*) builder;
+ (warning_config_msgBuilder*) builder;
+ (warning_config_msgBuilder*) builderWithPrototype:(warning_config_msg*) prototype;
- (warning_config_msgBuilder*) toBuilder;

+ (warning_config_msg*) parseFromData:(NSData*) data;
+ (warning_config_msg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (warning_config_msg*) parseFromInputStream:(NSInputStream*) input;
+ (warning_config_msg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (warning_config_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (warning_config_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface warning_config_msgBuilder : PBGeneratedMessageBuilder {
@private
  warning_config_msg* resultWarningConfigMsg;
}

- (warning_config_msg*) defaultInstance;

- (warning_config_msgBuilder*) clear;
- (warning_config_msgBuilder*) clone;

- (warning_config_msg*) build;
- (warning_config_msg*) buildPartial;

- (warning_config_msgBuilder*) mergeFrom:(warning_config_msg*) other;
- (warning_config_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (warning_config_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUid;
- (UInt32) uid;
- (warning_config_msgBuilder*) setUid:(UInt32) value;
- (warning_config_msgBuilder*) clearUid;

- (BOOL) hasStockCode;
- (NSString*) stockCode;
- (warning_config_msgBuilder*) setStockCode:(NSString*) value;
- (warning_config_msgBuilder*) clearStockCode;
@end

#define warning_config_result_msg_uid @"uid"
#define warning_config_result_msg_config_data @"configData"
@interface warning_config_result_msg : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUid_:1;
  UInt32 uid;
  NSMutableArray * configDataArray;
}
- (BOOL) hasUid;
@property (readonly) UInt32 uid;
@property (readonly, strong) NSArray * configData;
- (warning_config_data*)configDataAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (warning_config_result_msgBuilder*) builder;
+ (warning_config_result_msgBuilder*) builder;
+ (warning_config_result_msgBuilder*) builderWithPrototype:(warning_config_result_msg*) prototype;
- (warning_config_result_msgBuilder*) toBuilder;

+ (warning_config_result_msg*) parseFromData:(NSData*) data;
+ (warning_config_result_msg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (warning_config_result_msg*) parseFromInputStream:(NSInputStream*) input;
+ (warning_config_result_msg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (warning_config_result_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (warning_config_result_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface warning_config_result_msgBuilder : PBGeneratedMessageBuilder {
@private
  warning_config_result_msg* resultWarningConfigResultMsg;
}

- (warning_config_result_msg*) defaultInstance;

- (warning_config_result_msgBuilder*) clear;
- (warning_config_result_msgBuilder*) clone;

- (warning_config_result_msg*) build;
- (warning_config_result_msg*) buildPartial;

- (warning_config_result_msgBuilder*) mergeFrom:(warning_config_result_msg*) other;
- (warning_config_result_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (warning_config_result_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUid;
- (UInt32) uid;
- (warning_config_result_msgBuilder*) setUid:(UInt32) value;
- (warning_config_result_msgBuilder*) clearUid;

- (NSMutableArray *)configData;
- (warning_config_data*)configDataAtIndex:(NSUInteger)index;
- (warning_config_result_msgBuilder *)addConfigData:(warning_config_data*)value;
- (warning_config_result_msgBuilder *)setConfigDataArray:(NSArray *)array;
- (warning_config_result_msgBuilder *)clearConfigData;
@end

#define warning_user_all_stock_status_msg_uid @"uid"
@interface warning_user_all_stock_status_msg : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUid_:1;
  UInt32 uid;
}
- (BOOL) hasUid;
@property (readonly) UInt32 uid;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (warning_user_all_stock_status_msgBuilder*) builder;
+ (warning_user_all_stock_status_msgBuilder*) builder;
+ (warning_user_all_stock_status_msgBuilder*) builderWithPrototype:(warning_user_all_stock_status_msg*) prototype;
- (warning_user_all_stock_status_msgBuilder*) toBuilder;

+ (warning_user_all_stock_status_msg*) parseFromData:(NSData*) data;
+ (warning_user_all_stock_status_msg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (warning_user_all_stock_status_msg*) parseFromInputStream:(NSInputStream*) input;
+ (warning_user_all_stock_status_msg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (warning_user_all_stock_status_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (warning_user_all_stock_status_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface warning_user_all_stock_status_msgBuilder : PBGeneratedMessageBuilder {
@private
  warning_user_all_stock_status_msg* resultWarningUserAllStockStatusMsg;
}

- (warning_user_all_stock_status_msg*) defaultInstance;

- (warning_user_all_stock_status_msgBuilder*) clear;
- (warning_user_all_stock_status_msgBuilder*) clone;

- (warning_user_all_stock_status_msg*) build;
- (warning_user_all_stock_status_msg*) buildPartial;

- (warning_user_all_stock_status_msgBuilder*) mergeFrom:(warning_user_all_stock_status_msg*) other;
- (warning_user_all_stock_status_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (warning_user_all_stock_status_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUid;
- (UInt32) uid;
- (warning_user_all_stock_status_msgBuilder*) setUid:(UInt32) value;
- (warning_user_all_stock_status_msgBuilder*) clearUid;
@end

#define warning_user_all_stock_status_result_msg_uid @"uid"
#define warning_user_all_stock_status_result_msg_stock_status @"stockStatus"
@interface warning_user_all_stock_status_result_msg : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUid_:1;
  UInt32 uid;
  NSMutableArray * stockStatusArray;
}
- (BOOL) hasUid;
@property (readonly) UInt32 uid;
@property (readonly, strong) NSArray * stockStatus;
- (user_warning_stock_status*)stockStatusAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (warning_user_all_stock_status_result_msgBuilder*) builder;
+ (warning_user_all_stock_status_result_msgBuilder*) builder;
+ (warning_user_all_stock_status_result_msgBuilder*) builderWithPrototype:(warning_user_all_stock_status_result_msg*) prototype;
- (warning_user_all_stock_status_result_msgBuilder*) toBuilder;

+ (warning_user_all_stock_status_result_msg*) parseFromData:(NSData*) data;
+ (warning_user_all_stock_status_result_msg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (warning_user_all_stock_status_result_msg*) parseFromInputStream:(NSInputStream*) input;
+ (warning_user_all_stock_status_result_msg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (warning_user_all_stock_status_result_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (warning_user_all_stock_status_result_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface warning_user_all_stock_status_result_msgBuilder : PBGeneratedMessageBuilder {
@private
  warning_user_all_stock_status_result_msg* resultWarningUserAllStockStatusResultMsg;
}

- (warning_user_all_stock_status_result_msg*) defaultInstance;

- (warning_user_all_stock_status_result_msgBuilder*) clear;
- (warning_user_all_stock_status_result_msgBuilder*) clone;

- (warning_user_all_stock_status_result_msg*) build;
- (warning_user_all_stock_status_result_msg*) buildPartial;

- (warning_user_all_stock_status_result_msgBuilder*) mergeFrom:(warning_user_all_stock_status_result_msg*) other;
- (warning_user_all_stock_status_result_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (warning_user_all_stock_status_result_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUid;
- (UInt32) uid;
- (warning_user_all_stock_status_result_msgBuilder*) setUid:(UInt32) value;
- (warning_user_all_stock_status_result_msgBuilder*) clearUid;

- (NSMutableArray *)stockStatus;
- (user_warning_stock_status*)stockStatusAtIndex:(NSUInteger)index;
- (warning_user_all_stock_status_result_msgBuilder *)addStockStatus:(user_warning_stock_status*)value;
- (warning_user_all_stock_status_result_msgBuilder *)setStockStatusArray:(NSArray *)array;
- (warning_user_all_stock_status_result_msgBuilder *)clearStockStatus;
@end

#define delete_warning_config_form_code_msg_uid @"uid"
#define delete_warning_config_form_code_msg_stock_code @"stockCode"
@interface delete_warning_config_form_code_msg : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasStockCode_:1;
  BOOL hasUid_:1;
  NSString* stockCode;
  UInt32 uid;
}
- (BOOL) hasUid;
- (BOOL) hasStockCode;
@property (readonly) UInt32 uid;
@property (readonly, strong) NSString* stockCode;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (delete_warning_config_form_code_msgBuilder*) builder;
+ (delete_warning_config_form_code_msgBuilder*) builder;
+ (delete_warning_config_form_code_msgBuilder*) builderWithPrototype:(delete_warning_config_form_code_msg*) prototype;
- (delete_warning_config_form_code_msgBuilder*) toBuilder;

+ (delete_warning_config_form_code_msg*) parseFromData:(NSData*) data;
+ (delete_warning_config_form_code_msg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (delete_warning_config_form_code_msg*) parseFromInputStream:(NSInputStream*) input;
+ (delete_warning_config_form_code_msg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (delete_warning_config_form_code_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (delete_warning_config_form_code_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface delete_warning_config_form_code_msgBuilder : PBGeneratedMessageBuilder {
@private
  delete_warning_config_form_code_msg* resultDeleteWarningConfigFormCodeMsg;
}

- (delete_warning_config_form_code_msg*) defaultInstance;

- (delete_warning_config_form_code_msgBuilder*) clear;
- (delete_warning_config_form_code_msgBuilder*) clone;

- (delete_warning_config_form_code_msg*) build;
- (delete_warning_config_form_code_msg*) buildPartial;

- (delete_warning_config_form_code_msgBuilder*) mergeFrom:(delete_warning_config_form_code_msg*) other;
- (delete_warning_config_form_code_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (delete_warning_config_form_code_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUid;
- (UInt32) uid;
- (delete_warning_config_form_code_msgBuilder*) setUid:(UInt32) value;
- (delete_warning_config_form_code_msgBuilder*) clearUid;

- (BOOL) hasStockCode;
- (NSString*) stockCode;
- (delete_warning_config_form_code_msgBuilder*) setStockCode:(NSString*) value;
- (delete_warning_config_form_code_msgBuilder*) clearStockCode;
@end

#define delete_warning_config_result_form_code_msg_status @"status"
@interface delete_warning_config_result_form_code_msg : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasStatus_:1;
  UInt32 status;
}
- (BOOL) hasStatus;
@property (readonly) UInt32 status;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (delete_warning_config_result_form_code_msgBuilder*) builder;
+ (delete_warning_config_result_form_code_msgBuilder*) builder;
+ (delete_warning_config_result_form_code_msgBuilder*) builderWithPrototype:(delete_warning_config_result_form_code_msg*) prototype;
- (delete_warning_config_result_form_code_msgBuilder*) toBuilder;

+ (delete_warning_config_result_form_code_msg*) parseFromData:(NSData*) data;
+ (delete_warning_config_result_form_code_msg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (delete_warning_config_result_form_code_msg*) parseFromInputStream:(NSInputStream*) input;
+ (delete_warning_config_result_form_code_msg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (delete_warning_config_result_form_code_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (delete_warning_config_result_form_code_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface delete_warning_config_result_form_code_msgBuilder : PBGeneratedMessageBuilder {
@private
  delete_warning_config_result_form_code_msg* resultDeleteWarningConfigResultFormCodeMsg;
}

- (delete_warning_config_result_form_code_msg*) defaultInstance;

- (delete_warning_config_result_form_code_msgBuilder*) clear;
- (delete_warning_config_result_form_code_msgBuilder*) clone;

- (delete_warning_config_result_form_code_msg*) build;
- (delete_warning_config_result_form_code_msg*) buildPartial;

- (delete_warning_config_result_form_code_msgBuilder*) mergeFrom:(delete_warning_config_result_form_code_msg*) other;
- (delete_warning_config_result_form_code_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (delete_warning_config_result_form_code_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (UInt32) status;
- (delete_warning_config_result_form_code_msgBuilder*) setStatus:(UInt32) value;
- (delete_warning_config_result_form_code_msgBuilder*) clearStatus;
@end

#define set_warning_config_msg_uid @"uid"
#define set_warning_config_msg_stock_code @"stockCode"
#define set_warning_config_msg_config_data @"configData"
@interface set_warning_config_msg : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasStockCode_:1;
  BOOL hasUid_:1;
  NSString* stockCode;
  UInt32 uid;
  NSMutableArray * configDataArray;
}
- (BOOL) hasUid;
- (BOOL) hasStockCode;
@property (readonly) UInt32 uid;
@property (readonly, strong) NSString* stockCode;
@property (readonly, strong) NSArray * configData;
- (warning_config_data*)configDataAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (set_warning_config_msgBuilder*) builder;
+ (set_warning_config_msgBuilder*) builder;
+ (set_warning_config_msgBuilder*) builderWithPrototype:(set_warning_config_msg*) prototype;
- (set_warning_config_msgBuilder*) toBuilder;

+ (set_warning_config_msg*) parseFromData:(NSData*) data;
+ (set_warning_config_msg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (set_warning_config_msg*) parseFromInputStream:(NSInputStream*) input;
+ (set_warning_config_msg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (set_warning_config_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (set_warning_config_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface set_warning_config_msgBuilder : PBGeneratedMessageBuilder {
@private
  set_warning_config_msg* resultSetWarningConfigMsg;
}

- (set_warning_config_msg*) defaultInstance;

- (set_warning_config_msgBuilder*) clear;
- (set_warning_config_msgBuilder*) clone;

- (set_warning_config_msg*) build;
- (set_warning_config_msg*) buildPartial;

- (set_warning_config_msgBuilder*) mergeFrom:(set_warning_config_msg*) other;
- (set_warning_config_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (set_warning_config_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUid;
- (UInt32) uid;
- (set_warning_config_msgBuilder*) setUid:(UInt32) value;
- (set_warning_config_msgBuilder*) clearUid;

- (BOOL) hasStockCode;
- (NSString*) stockCode;
- (set_warning_config_msgBuilder*) setStockCode:(NSString*) value;
- (set_warning_config_msgBuilder*) clearStockCode;

- (NSMutableArray *)configData;
- (warning_config_data*)configDataAtIndex:(NSUInteger)index;
- (set_warning_config_msgBuilder *)addConfigData:(warning_config_data*)value;
- (set_warning_config_msgBuilder *)setConfigDataArray:(NSArray *)array;
- (set_warning_config_msgBuilder *)clearConfigData;
@end

#define set_warning_config_result_msg_status @"status"
@interface set_warning_config_result_msg : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasStatus_:1;
  UInt32 status;
}
- (BOOL) hasStatus;
@property (readonly) UInt32 status;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (set_warning_config_result_msgBuilder*) builder;
+ (set_warning_config_result_msgBuilder*) builder;
+ (set_warning_config_result_msgBuilder*) builderWithPrototype:(set_warning_config_result_msg*) prototype;
- (set_warning_config_result_msgBuilder*) toBuilder;

+ (set_warning_config_result_msg*) parseFromData:(NSData*) data;
+ (set_warning_config_result_msg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (set_warning_config_result_msg*) parseFromInputStream:(NSInputStream*) input;
+ (set_warning_config_result_msg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (set_warning_config_result_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (set_warning_config_result_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface set_warning_config_result_msgBuilder : PBGeneratedMessageBuilder {
@private
  set_warning_config_result_msg* resultSetWarningConfigResultMsg;
}

- (set_warning_config_result_msg*) defaultInstance;

- (set_warning_config_result_msgBuilder*) clear;
- (set_warning_config_result_msgBuilder*) clone;

- (set_warning_config_result_msg*) build;
- (set_warning_config_result_msg*) buildPartial;

- (set_warning_config_result_msgBuilder*) mergeFrom:(set_warning_config_result_msg*) other;
- (set_warning_config_result_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (set_warning_config_result_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (UInt32) status;
- (set_warning_config_result_msgBuilder*) setStatus:(UInt32) value;
- (set_warning_config_result_msgBuilder*) clearStatus;
@end

#define warning_stock_value_value @"value"
@interface warning_stock_value : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasValue_:1;
  Float64 value;
}
- (BOOL) hasValue;
@property (readonly) Float64 value;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (warning_stock_valueBuilder*) builder;
+ (warning_stock_valueBuilder*) builder;
+ (warning_stock_valueBuilder*) builderWithPrototype:(warning_stock_value*) prototype;
- (warning_stock_valueBuilder*) toBuilder;

+ (warning_stock_value*) parseFromData:(NSData*) data;
+ (warning_stock_value*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (warning_stock_value*) parseFromInputStream:(NSInputStream*) input;
+ (warning_stock_value*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (warning_stock_value*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (warning_stock_value*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface warning_stock_valueBuilder : PBGeneratedMessageBuilder {
@private
  warning_stock_value* resultWarningStockValue;
}

- (warning_stock_value*) defaultInstance;

- (warning_stock_valueBuilder*) clear;
- (warning_stock_valueBuilder*) clone;

- (warning_stock_value*) build;
- (warning_stock_value*) buildPartial;

- (warning_stock_valueBuilder*) mergeFrom:(warning_stock_value*) other;
- (warning_stock_valueBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (warning_stock_valueBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasValue;
- (Float64) value;
- (warning_stock_valueBuilder*) setValue:(Float64) value;
- (warning_stock_valueBuilder*) clearValue;
@end

#define warning_record_code @"code"
#define warning_record_name @"name"
#define warning_record_node @"node"
@interface warning_record : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasCode_:1;
  BOOL hasName_:1;
  NSString* code;
  NSString* name;
  NSMutableArray * nodeArray;
}
- (BOOL) hasCode;
- (BOOL) hasName;
@property (readonly, strong) NSString* code;
@property (readonly, strong) NSString* name;
@property (readonly, strong) NSArray * node;
- (warning_recordwarning_msg_node*)nodeAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (warning_recordBuilder*) builder;
+ (warning_recordBuilder*) builder;
+ (warning_recordBuilder*) builderWithPrototype:(warning_record*) prototype;
- (warning_recordBuilder*) toBuilder;

+ (warning_record*) parseFromData:(NSData*) data;
+ (warning_record*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (warning_record*) parseFromInputStream:(NSInputStream*) input;
+ (warning_record*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (warning_record*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (warning_record*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

#define warning_msg_node_warning_type @"warningType"
#define warning_msg_node_sub_msg @"subMsg"
#define warning_msg_node_time @"time"
@interface warning_recordwarning_msg_node : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasSubMsg_:1;
  BOOL hasTime_:1;
  BOOL hasWarningType_:1;
  NSData* subMsg;
  UInt32 time;
  enum_warning_type warningType;
}
- (BOOL) hasWarningType;
- (BOOL) hasSubMsg;
- (BOOL) hasTime;
@property (readonly) enum_warning_type warningType;
@property (readonly, strong) NSData* subMsg;
@property (readonly) UInt32 time;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (warning_recordwarning_msg_nodeBuilder*) builder;
+ (warning_recordwarning_msg_nodeBuilder*) builder;
+ (warning_recordwarning_msg_nodeBuilder*) builderWithPrototype:(warning_recordwarning_msg_node*) prototype;
- (warning_recordwarning_msg_nodeBuilder*) toBuilder;

+ (warning_recordwarning_msg_node*) parseFromData:(NSData*) data;
+ (warning_recordwarning_msg_node*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (warning_recordwarning_msg_node*) parseFromInputStream:(NSInputStream*) input;
+ (warning_recordwarning_msg_node*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (warning_recordwarning_msg_node*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (warning_recordwarning_msg_node*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface warning_recordwarning_msg_nodeBuilder : PBGeneratedMessageBuilder {
@private
  warning_recordwarning_msg_node* resultWarningMsgNode;
}

- (warning_recordwarning_msg_node*) defaultInstance;

- (warning_recordwarning_msg_nodeBuilder*) clear;
- (warning_recordwarning_msg_nodeBuilder*) clone;

- (warning_recordwarning_msg_node*) build;
- (warning_recordwarning_msg_node*) buildPartial;

- (warning_recordwarning_msg_nodeBuilder*) mergeFrom:(warning_recordwarning_msg_node*) other;
- (warning_recordwarning_msg_nodeBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (warning_recordwarning_msg_nodeBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasWarningType;
- (enum_warning_type) warningType;
- (warning_recordwarning_msg_nodeBuilder*) setWarningType:(enum_warning_type) value;
- (warning_recordwarning_msg_nodeBuilder*) clearWarningType;

- (BOOL) hasSubMsg;
- (NSData*) subMsg;
- (warning_recordwarning_msg_nodeBuilder*) setSubMsg:(NSData*) value;
- (warning_recordwarning_msg_nodeBuilder*) clearSubMsg;

- (BOOL) hasTime;
- (UInt32) time;
- (warning_recordwarning_msg_nodeBuilder*) setTime:(UInt32) value;
- (warning_recordwarning_msg_nodeBuilder*) clearTime;
@end

@interface warning_recordBuilder : PBGeneratedMessageBuilder {
@private
  warning_record* resultWarningRecord;
}

- (warning_record*) defaultInstance;

- (warning_recordBuilder*) clear;
- (warning_recordBuilder*) clone;

- (warning_record*) build;
- (warning_record*) buildPartial;

- (warning_recordBuilder*) mergeFrom:(warning_record*) other;
- (warning_recordBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (warning_recordBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCode;
- (NSString*) code;
- (warning_recordBuilder*) setCode:(NSString*) value;
- (warning_recordBuilder*) clearCode;

- (BOOL) hasName;
- (NSString*) name;
- (warning_recordBuilder*) setName:(NSString*) value;
- (warning_recordBuilder*) clearName;

- (NSMutableArray *)node;
- (warning_recordwarning_msg_node*)nodeAtIndex:(NSUInteger)index;
- (warning_recordBuilder *)addNode:(warning_recordwarning_msg_node*)value;
- (warning_recordBuilder *)setNodeArray:(NSArray *)array;
- (warning_recordBuilder *)clearNode;
@end

#define get_warning_record_from_uid_msg_uid @"uid"
@interface get_warning_record_from_uid_msg : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUid_:1;
  UInt32 uid;
}
- (BOOL) hasUid;
@property (readonly) UInt32 uid;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (get_warning_record_from_uid_msgBuilder*) builder;
+ (get_warning_record_from_uid_msgBuilder*) builder;
+ (get_warning_record_from_uid_msgBuilder*) builderWithPrototype:(get_warning_record_from_uid_msg*) prototype;
- (get_warning_record_from_uid_msgBuilder*) toBuilder;

+ (get_warning_record_from_uid_msg*) parseFromData:(NSData*) data;
+ (get_warning_record_from_uid_msg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (get_warning_record_from_uid_msg*) parseFromInputStream:(NSInputStream*) input;
+ (get_warning_record_from_uid_msg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (get_warning_record_from_uid_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (get_warning_record_from_uid_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface get_warning_record_from_uid_msgBuilder : PBGeneratedMessageBuilder {
@private
  get_warning_record_from_uid_msg* resultGetWarningRecordFromUidMsg;
}

- (get_warning_record_from_uid_msg*) defaultInstance;

- (get_warning_record_from_uid_msgBuilder*) clear;
- (get_warning_record_from_uid_msgBuilder*) clone;

- (get_warning_record_from_uid_msg*) build;
- (get_warning_record_from_uid_msg*) buildPartial;

- (get_warning_record_from_uid_msgBuilder*) mergeFrom:(get_warning_record_from_uid_msg*) other;
- (get_warning_record_from_uid_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (get_warning_record_from_uid_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUid;
- (UInt32) uid;
- (get_warning_record_from_uid_msgBuilder*) setUid:(UInt32) value;
- (get_warning_record_from_uid_msgBuilder*) clearUid;
@end

#define get_warning_record_from_uid_result_msg_uid @"uid"
#define get_warning_record_from_uid_result_msg_record @"record"
@interface get_warning_record_from_uid_result_msg : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUid_:1;
  UInt32 uid;
  NSMutableArray * recordArray;
}
- (BOOL) hasUid;
@property (readonly) UInt32 uid;
@property (readonly, strong) NSArray * record;
- (warning_record*)recordAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (get_warning_record_from_uid_result_msgBuilder*) builder;
+ (get_warning_record_from_uid_result_msgBuilder*) builder;
+ (get_warning_record_from_uid_result_msgBuilder*) builderWithPrototype:(get_warning_record_from_uid_result_msg*) prototype;
- (get_warning_record_from_uid_result_msgBuilder*) toBuilder;

+ (get_warning_record_from_uid_result_msg*) parseFromData:(NSData*) data;
+ (get_warning_record_from_uid_result_msg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (get_warning_record_from_uid_result_msg*) parseFromInputStream:(NSInputStream*) input;
+ (get_warning_record_from_uid_result_msg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (get_warning_record_from_uid_result_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (get_warning_record_from_uid_result_msg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface get_warning_record_from_uid_result_msgBuilder : PBGeneratedMessageBuilder {
@private
  get_warning_record_from_uid_result_msg* resultGetWarningRecordFromUidResultMsg;
}

- (get_warning_record_from_uid_result_msg*) defaultInstance;

- (get_warning_record_from_uid_result_msgBuilder*) clear;
- (get_warning_record_from_uid_result_msgBuilder*) clone;

- (get_warning_record_from_uid_result_msg*) build;
- (get_warning_record_from_uid_result_msg*) buildPartial;

- (get_warning_record_from_uid_result_msgBuilder*) mergeFrom:(get_warning_record_from_uid_result_msg*) other;
- (get_warning_record_from_uid_result_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (get_warning_record_from_uid_result_msgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUid;
- (UInt32) uid;
- (get_warning_record_from_uid_result_msgBuilder*) setUid:(UInt32) value;
- (get_warning_record_from_uid_result_msgBuilder*) clearUid;

- (NSMutableArray *)record;
- (warning_record*)recordAtIndex:(NSUInteger)index;
- (get_warning_record_from_uid_result_msgBuilder *)addRecord:(warning_record*)value;
- (get_warning_record_from_uid_result_msgBuilder *)setRecordArray:(NSArray *)array;
- (get_warning_record_from_uid_result_msgBuilder *)clearRecord;
@end


// @@protoc_insertion_point(global_scope)
